### ISSUE TITLE
Unable to run the project after cloned. Using docker and their compose files

### ISSUE THREAD

**Issue by mahmudoni** [chirpstack/chirpstack#107]
chirpstack_chirpstack-ui_1 exited with code 0
branch im on : master
steps to reproduce.
1. clone the repo
2. install docker and docker compose
3. run 'docker-compose build'
4. run 'docker-compose up'. 

ignore the -d command so that you can see the error logs or console outputs.

**Comment by brocaar** [comment]
Please see the docs how to use the Docker Compose environment: https://www.chirpstack.io/docs/chirpstack/contribute.html

**Comment by mahmudoni** [comment]
these are the errors I've got. I followed the instruction as described here  https://www.chirpstack.io/docs/chirpstack/contribute.html

I did run 'serve -s build' but webpage showing 404 error 
![image](https://user-images.githubusercontent.com/78255122/220867153-f7756eca-6798-48e9-8563-c10e175b1e6e.png)
![image](https://user-images.githubusercontent.com/78255122/220867363-cf54e29e-dc83-4500-9156-19f469e77f7c.png)
