### ISSUE TITLE
Unable to list ADR algorithms for device profile using gRPC

### ISSUE THREAD

**Issue by WillooWisp** [chirpstack/chirpstack#112]
Hi,

I am trying to create a device profile programmatically using gRPC, since I need to list the available ADR algorithms in order to set the proper AdrAlgorithmId of the device profile to create.

I have generated the C# client classes from your proto files using your docker compose setup. I am successfully using many of the other clients and their gRPC methods, but this one below does not seem correct since it does not authenticate even though I pass in the authentication bearer token as for all other successful client calls.

**Exception**
Grpc.Core.RpcException: 'Status(StatusCode="Unauthenticated", Detail="")'

```
var headers = new Metadata
{
    { "Authorization", $"Bearer {apiKey}" }
};

var deviceProfileClient = new DeviceProfileServiceClient(channel);
var response = await deviceProfileClient.ListAdrAlgorithmsAsync(new Empty(), headers);
```

**Comment by WillooWisp** [comment]
Any ideas anyone?

**Comment by brocaar** [comment]
I have found the issue. The authorization checks for an active use, it should be an active user or active API key (the latter is currently rejected).

**Comment by WillooWisp** [comment]
Okay, good to hear. Do you have a timeframe for a release with the fix?
