### ISSUE TITLE
MQTT Integration json events do not adhere to the protobuf definition

### ISSUE THREAD

**Issue by ederuiter** [chirpstack/chirpstack#116]
I am writing an mqtt integration in golang and as the integration event definitions (imported from `github.com/chirpstack/chirpstack/api/go/v4/integration`)  do contain the necessary `json:".."` annotations I was hoping to be able to use something like this to decode an uplinkevent:

```golang
event := &integration.UplinkEvent{}
_ = json.Unmarshal(msg.Payload(), event)
fmt.Printf("Received: %+v\n", event)
```

This works for some fields, but for most fields (eg: DeviceInfo, RxInfo, TxInfo) this does not work as the data received mqtt does not seem to adhere to the json field names specified in the integration event definition. 
For example see: https://github.com/chirpstack/chirpstack/blob/master/api/go/integration/integration.pb.go#L288 where the json field is defined as `device_info` but in the integration event it is sent as `deviceInfo`

This is the raw json we receive
```json
 {"deduplicationId":"1caa3b80-9a09-4b8e-a244-9c4bef5f169c","time":"2023-02-11T11:59:27.902047+00:00","deviceInfo":{"tenantId":"52f14cd4-c6f1-4fbd-8f87-4025e1d49242","tenantName":"ChirpStack","applicationId":"00372e31-0620-4671-8270-237632a4e227","applicationName":"[281] TEST_GATEWAY","deviceProfileId":"1593e74b-6c04-4dcc-b280-6f9bf87c2bb2","deviceProfileName":"A84041DB2184D988","deviceName":"A84041DB2184D988","devEui":"a84041db2184d988","tags":{}},"devAddr":"00000001","adr":true,"dr":5,"fCnt":5,"fPort":2,"confirmed":true,"data":"BYIIAlgeoKU=","rxInfo":[{"gatewayId":"a84041ffff249aac","uplinkId":27545,"time":"2023-02-11T11:59:27.902047+00:00","rssi":-44,"snr":13.8,"channel":1,"rfChain":1,"location":{},"context":"0u4nEA==","metadata":{"region_config_id":"eu868","region_common_name":"EU868"},"crcStatus":"CRC_OK"}],"txInfo":{"frequency":868300000,"modulation":{"lora":{"bandwidth":125000,"spreadingFactor":7,"codeRate":"CR_4_5"}}}}
 ```
Unmarshalled with the code above it looks like this:
```
Received: &{state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:<nil>} sizeCache:0 unknownFields:[] DeduplicationId: Time: DeviceInfo:<nil> DevAddr: Adr:true Dr:5 FCnt:0 FPort:0 Confirmed:true Data:[5 130 8 2 88 30 160 165] Object:<nil> RxInfo:[] TxInfo:<nil>}
```

Disclaimer: I don't know if this is supposed to be used this way (although the docs [mention](https://www.chirpstack.io/docs/chirpstack/integrations/events.html) ` JSON based on the Protocol Buffers JSON mapping`), if there is a better way of unmarshalling an integration event in go please let me know.

**Comment by brocaar** [comment]
Protobuf has a different way of JSON encoding, therefore you must use the Protobuf JSON unmarshaling (provided by `google.golang.org/protobuf/encoding/protojson`). For an example please see: https://www.chirpstack.io/docs/chirpstack/integrations/http.html#go.

Specifically, see:

```go
        return protojson.UnmarshalOptions{
            DiscardUnknown: true,
            AllowPartial:   true,
        }.Unmarshal(b, v)
```
