### ISSUE TITLE
chirpstack V4: Only EU868 is selectable in Device Profile -> Region configuration

### ISSUE THREAD

**Issue by t0mZ4** [chirpstack/chirpstack#120]
using latest version, setting up device profile, in region configuration only EU868 is available, even when chosing another region.

![image](https://user-images.githubusercontent.com/31729091/219383130-91de7dc8-a6d1-41a6-9c67-7126d6eba2f5.png)

**Comment by brocaar** [comment]
I can reproduce this in case the `description` is not set in the `region_XXXX.toml` file. In this case, an incorrect fallback is being used. I will fix this in the next release. As a short-term (and proper) solution, please define a `description` config parameter, for example:

https://github.com/chirpstack/chirpstack/blob/master/chirpstack/configuration/region_us915_0.toml#L7

**Comment by brocaar** [comment]
The above commit fixes the issue.
