### ISSUE TITLE
Put back fCnt in ChirpStack v4

### ISSUE THREAD

**Issue by IoTThinks** [chirpstack/chirpstack#121]
Hi ChirpStack team,
I remember in ChirpStack v3, we have fCnt in the Web GUI.
This is removed in ChirpStack v4. We have to click on the (+) to see the fCnt.
The fCnt is very useful to monitor if any packets are lost or if the device has been rebooted.

![image](https://user-images.githubusercontent.com/29994971/219855098-23f32e16-2998-412d-a68f-e67dd59d19cb.png)

So I think it is useful to bring fCnt back in the above GUI.
Thanks a lot and have a nice day.

**Comment by brocaar** [comment]
@IoTThinks this has been implemented by the above commit :)

**Comment by IoTThinks** [comment]
@brocaar I tested just now. Confirmed working. 
Thanks a lot.
