### ISSUE TITLE
Running the source code

### ISSUE THREAD

**Issue by mjlaurent6** [chirpstack/chirpstack#157]
Hi i am trying to run the source code version of chirpstack (not the chirpstack-docker version).

When i run `docker-compose up`, 
i only get the kafka, redis, rabbitmq ... container running except the ui and chirpstack. 
Both exited with code 0, 

May i know what is the workflow of developing the source code ? 

What i did so far

1. Clone this repo 
2. `docker-compose up`

I tried several `make` commands but still the same

**Comment by z-lionel** [comment]
i have some question, may i ask how to fix it
