### ISSUE TITLE
[Feature Request] - Display Chirpstack Version and Hint for Updates in UI

### ISSUE THREAD

**Issue by benchvondaranch** [chirpstack/chirpstack#158]
Hi All,

As a ChirpStack user, it would be helpful to **see the version number of ChirpStack displayed in the user interface**. This feature would enable users to keep track of the ChirpStack version they are running, which is crucial when troubleshooting issues and ensuring that the software is up-to-date with the latest security patches.

Furthermore, it would be beneficial to receive a hint in the UI when a new version of ChirpStack becomes available. This would enable users to easily check for updates and ensure that they are running the most recent version.

To implement this feature, a small text or badge element could be added to the UI to show the current ChirpStack version. When a new version is available, this element could change color or display an icon to indicate that an update is ready. Clicking on the element could provide more details about the update and instructions for upgrading.

Here is an example like Portainer did this:
![Portainer_VersionNumber_Example](https://user-images.githubusercontent.com/31693685/229850754-8fbf1848-af87-4435-acd7-d2c93bf6f4d1.png)

Thanks in advance,
benchvondaranch

**Comment by brocaar** [comment]
The above commit implements showing the current version. For now I'll wait with showing an update notification as this requires some additional infrastructure a the chirpstack.io server-side (API to retrieve latest version).
