### ISSUE TITLE
Chispstack initialization status

### ISSUE THREAD

**Issue by robsonos** [chirpstack/chirpstack#169]
Hi all,

Any way to know when the application has finished its initialization? I tested two different approaches: watching the logs and watching the `__diesel_schema_migrations` table. They work but I am not happy with those approaches.

Cheers.

**Comment by brocaar** [comment]
I think the `/health` endpoint should provide you with such indication. See the configuration:

```
# Monitoring related configuration.
[monitoring]

  # interface:port to bind the monitoring endpoint to (optional).
  #
  # /health  - Returns 200 in case the healthchecks have passed.
  # /metrics - Returns metrics which can be scraped by Prometheus.
  #
  # If not set, this endpoint will be disabled.
  bind=""
```

https://www.chirpstack.io/docs/chirpstack/configuration.html
