### ISSUE TITLE
LoRaWAN IPv6 support?

### ISSUE THREAD

**Issue by kpwebb** [chirpstack/chirpstack#173]
Hi, 

I'm curious if there's been any discussion regarding the newly added support for IPv6 over LoRaWAN IPv6:

https://lora-alliance.org/lora-alliance-press-release/lora-alliance-launches-ipv6-over-lorawan-opens-wide-range-of-new-markets-for-lorawan/

This is relevant to my work, and am curious if this is feasible, and if help implementing this would be welcome?

**Comment by kpwebb** [comment]
Ah, just found this  thread and will follow up there: https://forum.chirpstack.io/t/using-chirpstack-on-ipv6-without-netids/16424/4

**Comment by brocaar** [comment]
I'm not 100% sure if that topic is about the same. What you are asking is about this I believe:
https://resources.lora-alliance.org/technical-specifications/ts010-1-0-0-ipv6-adaptation-layer

I have not looked at the details, but I believe this is an application-layer protocol on top of LoRaWAN, e.g. it could be built on top of ChirpStack (much like the FUOTA server).
