### ISSUE TITLE
Tutorials/Getting Started With gRPC API in Python

### ISSUE THREAD

**Issue by SlazyHW** [chirpstack/chirpstack#181]
Hello everyone,

I am a complete beginner and I need to read out the names and payloads of my end devices via gRPC. 
These already arrive at the Chirpstack GUI on the web server. 

Is there  a really detailed tutorial on how to write a gRPC client in Python to read out the data I want to obtain?
I never worked with anything like this and I am completely overwhelmed. 

https://pypi.org/project/chirpstack-api/

I already installed the API with the link above but I have no clue how to continue.

Thanks in advance.

**Comment by brocaar** [comment]
For receiving payload data, you might be interested in the HTTP integration, please see:
https://www.chirpstack.io/docs/chirpstack/integrations/http.html#python

For using the gRPC API (which is more for CRUD functions), please see this example:
https://www.chirpstack.io/docs/chirpstack/api/python-examples.html

As an alternative to the gRPC API, there is also a REST interface proxy:
https://github.com/chirpstack/chirpstack-rest-api

**Comment by SlazyHW** [comment]
Thank you! Will look through all of it.
