### ISSUE TITLE
Menu typos & changes

### ISSUE THREAD

**Issue by gristlekinginc** [chirpstack/chirpstack#185]
On the left hand menu, under Network Server
-capitalize K in API Keys
-remove dash between Device and Profile, and capitalize T in templates:  Device Profile Templates

Under Tenant:
-capitalize K in API Keys
-capitalize P in Profiles:  Device Profiles

**Comment by brocaar** [comment]
Thank you for your feedback? Would you like to create a PR for this? Please see this file:

https://github.com/chirpstack/chirpstack/blob/master/ui/src/components/Menu.tsx

**Comment by gristlekinginc** [comment]
Hi Orne,
I haven’t done a PR before and think I got it right.  Let me know if there’s anything else I need to do.
Cheers,
Nik

—
Gristle King Inc
San Diego, CA
