### ISSUE TITLE
MQTT connection name not used

### ISSUE THREAD

**Issue by FStefanni** [chirpstack/chirpstack#192]
Hi,

I have noted the following strange behavior.

If I look at the MQTT connections from my broker dashboard, I see the following:
```
ClientID             | Status    | IP
6afe474e807e32a9     | Connected | 10.53.128.33:60822
chirp-10.53.128.33   | Connected | 10.53.128.33:60826
chirp-10.53.128.218  | Connected | 10.53.128.218:52982
bcd3fc33c706bece     | Connected | 10.53.128.218:52978
```

As you can see:
* I have set up 2 replicas for chirpstack (ClientID prefix `chirp`)
* The ClientID is built by adding the `-<host ip>`

The client ID is the parameter set as MQTT client id.
So whats "wrong" is that there are two more connections, with a random ClientID, which are unexpected, belonging to the same hosts (it is seen by looking the IP column, they have the same IP).
Of course, since they are two connections (from each host), they must have a different ClientID name, so I understand that the second connection has a random name.
But I was expecting just a single connection for host (maybe with multiple subscriptions), so that the ClientID parameter actually "works".

Fixing this would be extremely useful when inspecting broker logs with thousand of connections, so that with a simple filter we can inspect the chirpstack related connections.

So I suggest:
* (preferred solution) to use a single connection
* (not so clean solution imho) to use the `client-id` parameter of the config file as a prefix to create two actual client IDs (e.g. `<client_id>-1` and `<client_id>-2`). Maybe in this case the configuration parameter should be renamed from `client_id` to something more relevant, as `client_id_prefix`

I am using chirpstack 4.3.2 on kubernetes.

Regards

**Comment by brocaar** [comment]
Please note that ChirpStack might connect twice because MQTT is used for the GW <> NS communication, but also as MQTT integration (which could be the same but also an other MQTT broker).

The config sections you might want to look into are:

* `[integration.mqtt]` (`chirpstack.toml`)
* ` [regions.gateway.backend.mqtt]` (`region_XXXXX.toml`)

Did you set the `client_id` for both sections?

**Comment by FStefanni** [comment]
Oh yes, you are right!
Thank you.
Regards
