### ISSUE TITLE
Device lock - can't schedule next queue item error=Get device lock

### ISSUE THREAD

**Issue by mvniekerk** [chirpstack/chirpstack#193]
Error in logs:
chirpstack-docker-chirpstack-1           | 2023-05-30T14:03:52.316006Z ERROR chirpstack::downlink::scheduler: Schedule next queue-item for device failed error=Get device lock

Can't send anything to the devices.

**Comment by mvniekerk** [comment]
I presume the locks are held in Redis. There's also no documentation how to clear said locks

**Comment by brocaar** [comment]
Could you share the steps to reproduce this issue + the configuration (changes) that you are using? Did you make any changes under `[network.scheduler]`?

**Comment by halukmy** [comment]
this is big problem, and stops to downlink to device!
![image](https://github.com/chirpstack/chirpstack/assets/2916333/32858a68-6544-40a4-8efb-bc2b4c4bf9e0)

**Comment by brocaar** [comment]
@halukmy I don't see anything wrong in your log. There are no errors and I see multiple downlinks being sent to the gateway.

I'm closing this issue as there hasn't been any response with regards to steps to reproduce this issue.
