### ISSUE TITLE
[feature request] Allow URL subpaths

### ISSUE THREAD

**Issue by FStefanni** [chirpstack/chirpstack#205]
Hi,

it could be very useful to allow to expose the following components in subpaths:

- The web UI
- The gRPC api
- The REST API

Moreover, in the case of gRPC and Web UI, subpaths could allow to expose both on the same port.

Allowing subpaths is extremely useful for example when using k8s, and also when exposing behind a reverse proxy.

Regards

**Comment by brocaar** [comment]
I agree this can be useful. Would you like to create a pull-request for this?
