### ISSUE TITLE
[feature request] Add tags to tenants

### ISSUE THREAD

**Issue by skiplyfrance** [chirpstack/chirpstack#211]
Hi,
Tags and metadata are great to build automations through API.
Adding tags to tenants could allow to apply automated behaviors at a global level.
For instance, instead of filling each gateway with an "alert webhook" url, we could apply the same url for the whole tenant.

**Comment by liangyuanpeng** [comment]
I agree with it,This can effectively reduce duplication of work.

**Comment by brocaar** [comment]
Here you go :-)
