### ISSUE TITLE
Chirpstack 4.0 customization (Implementing Application Server)

### ISSUE THREAD

**Issue by mwilniewiec** [chirpstack/chirpstack#213]
Hi, some time ago I was investigating Chirpstack a little bit and my conclusion was that possibly I need to write my own application server to solve things the way I want.
Now with Chirpstack 4.0 I was surprised that Application Server is gone :)
I still have a basic understanding of Lora concepts but I'll try to give you my idea.

Is there still a way of providing the application layer somehow in Chirpstack?
My problems:
1. I would like to handle downlink message queuing on my own (Im wondering why currently there is no message removal from the queue, there is only "flush". Is it a hard limitation or just API is missing such feature?).
2. Im not sure how chirpstack persists all the events / uplink data but I would like chirpstack stop doing that as with houndreds thousands of devices this is a waste of resources as Im still willing to keep this data the "my way".
3. I would like to join devices without adding them to the tenant application. I tried to implement my own join server but I can see that Im only receving JoinReq when device is already added in Chirpstack (at least EUI & Profile without OTA keys). I would like to setup only gateways in a tenant and somehow add the end-node to a tenant automatically during the joining process.
4. ... possibly more :)

Maybe some of my requirements doesnt make sense but Im still browsing and I have a feeling that while getting deeper into LORA and Chirpstack I would need more customization for a big IOT project.

**Comment by brocaar** [comment]
I think this question is more suited for the forum as this is not really a feature or bug request (or as part of commercial support as these questions might be specific to your needs). In summary:

1. I think this is just an API endpoint that hasn't been implemented. Feel free to create a feature-request or PR for this
2. ChirpStack does not store all events, only the last 10 items per device and gateway (for debugging purposes). This is configurable in the `chirpstack.toml` configuration.
3. This is not possible, but you could intercept join-request from MQTT and create devices if they do not already exist. Maybe this would cause the first join-request to fail, but then a retry would succeed.
