### ISSUE TITLE
[bug] Downlink is dropped if enqued before a join request

### ISSUE THREAD

**Issue by skiplyfrance** [chirpstack/chirpstack#216]
What I wanted to achieve:
I need to provision devices and enque a configuration downlink to set some parameters as soon as they join the newtork.

Step to reproduce
- Provision a device in OTAA
- Add a confirmed (or not) downlink in the queue 
- Inserted the batteries in the device.

The downlink is never sent to the device, and the queue is empty as if it was ok (even in the case of a confirmed DL)

**Comment by brocaar** [comment]
Please note that the default is to flush the queue on activate, please see this setting in the device-profile:

![image](https://github.com/chirpstack/chirpstack/assets/165497/15fded1c-58c0-4bc6-b9c3-037ccbe122cb)
