### ISSUE TITLE
Chirpstack service is getting aborted /stopped

### ISSUE THREAD

**Issue by pcsece411** [chirpstack/chirpstack#218]
Hi, 

We are using the Chirpstack version v4. Sometimes, we have observed that, chirpstack service is stopped abruptly.
When we analyzed the logs, before the service is stopped/aborted, observed below message.

**malloc(): unaligned tcache chunk detected**

![image](https://github.com/chirpstack/chirpstack/assets/17989399/d2aefe01-88f0-4752-a9d5-376842c79959)

After this, chirpstack service is getting stopped and we need to restart the service manually.

Can you please guide me on this.

Thank you!

Regards,
Chandrasekhar

**Comment by brocaar** [comment]
I have not seen this error myself yet. Could you please upgrade to v4.4.0 and confirm if you are still experiencing this issue?

**Comment by liangyuanpeng** [comment]
Have some reproduce would be great.

**Comment by pcsece411** [comment]
Hi @brocaar  and @liangyuanpeng , we have increased H/W configuration. RAM size from 4GB to 6GB(in virtual machine). Because we observed that, RAM utilization is 100% or near to 98%. After increasing the RAM size, we are not seeing the issue. But still, we will observe, if same issue can be occurred or not?

**Comment by brocaar** [comment]
I'm closing this issue as I'm not sure how to reproduce. As well it is not clear if this issue still occurs with v4.4.x+ (v4.4 has some significant changes related to dependency linking).
