### ISSUE TITLE
TLS for Redis connection

### ISSUE THREAD

**Issue by OldGrumpyViking** [chirpstack/chirpstack#219]
Hi

Chirpstack v3 has the option to enable TLS for the redis connection.
```yaml
[redis]
tls_enabled=true
```

Will this feature also become available for Chirpstack v4?

**Comment by OldGrumpyViking** [comment]
Possibly related to #170 and #128

**Comment by brocaar** [comment]
It is already available, you can use `rediss://...` instead of `redis://...`

**Comment by Pasukaru** [comment]
Please add this to the documentation / examples, I just found this issue after a long odyssey.

The examples only show this:
```
# Example formats:
#   redis://127.0.0.1:6379
#   redis://:password@127.0.0.1:6379
#   redis://username:password@127.0.0.1:6379
```

With no mention on how to enable TLS - or an exhaustive list of the available connection string options.

What worked for me now was `rediss://password@host:6380` for redis on azure cache.

**Comment by brocaar** [comment]
@Pasukaru see the above commit which adds this to the config template.
