### ISSUE TITLE
Connection of LoRa SX1278 433Mhz v1.0 with a Raspberry Pi 4 model B to send data to a gateway using ChirpStack ?

### ISSUE THREAD

**Issue by rukundob451** [chirpstack/chirpstack#226]
How does one connect LoRa SX1278 433Mhz v1.0 with a Raspberry Pi 4 model B to send data to a gateway using ChirpStack checked out and realized the Gateway Name called AdemneaGW has a Gateway Profile: RAK7249 WisGate Edge Max Gateway? I'll be glad for a positive response, thank you.

**Comment by brocaar** [comment]
I've seen that you have posted the same question on the forum (forum.chirpstack.io) already. That is a better place for such questions than GitHub issues (which is intended for feature and bug reports).
