### ISSUE TITLE
Allow option MQTT integration on local machine (and remote client) without need for MQTT certificate

### ISSUE THREAD

**Issue by trlafleur** [chirpstack/chirpstack#233]
There are cases where having read-write or read-only access to the MQTT stream is desirable without CA support.
As an option allow for MQTT integration to support full CA as now supported, but also provide read-only and read-write options with proper user name and password.

**Comment by bconway** [comment]
The wording of this issue is confusing to me. CA (or any other) certs have never been required for any MQTT functionality, including the MQTT integration. See, for example, the chirpstack-docker repo with MQTT integration enabled.

**Comment by trlafleur** [comment]
Maybe I'm confused, when I select application MQTT integration, all I get is a place to generate CA... 

I never see any application data in MQTT, gateway, and $SYS streams are active....
I'm assuming then that I am missing something to turn on application streams from MQTT??
but again, adding the option as I suggested would give options to secure MQTT without the need for a CA.

running the current RPI image, chirpstack-gateway-os-full-raspberrypi3-20230322153826.rootfs.wic.gz

**Comment by brocaar** [comment]
Maybe the UI could be improved (pull-requests welcome), but the MQTT integration card is only there for creating client-certificates in case you have configured your MQTT broker with client-certificate authentication (e.g. https://www.chirpstack.io/docs/guides/mosquitto-tls-configuration.html).

In case of the ChirpStack Gateway OS this is not the case, and you can directly subscribe to the local MQTT broker without the need to use any credentials / certificates.
