### ISSUE TITLE
Where do I find gateway-config code??

### ISSUE THREAD

**Issue by trlafleur** [chirpstack/chirpstack#244]
Where do I find gateway-config code??

also, Monit scripts use in pre-built images...

**Comment by brocaar** [comment]
You probably want to take a look at these repos:

* https://github.com/chirpstack/chirpstack-mqtt-forwarder
* https://github.com/chirpstack/chirpstack-gateway-bridge

**Comment by trlafleur** [comment]
When I use the pre-built images for RPI below, I see the below-listed commands on connection to the CLI.
Where do I find the code for gateway-config and the scripts for monit used to build the RPI image?

Unfortunately, I wasn't able to locate the code in your reference above....

also, do you have a time frame for when the pre-built RPI images will be updated??

Thanks

`Commands:
> sudo gateway-config  - configure the gateway
> sudo monit summary   - display service monitor
`

`https://artifacts.chirpstack.io/downloads/chirpstack-gateway-os/raspberrypi/raspberrypi4/4.1.1/`

**Comment by brocaar** [comment]
Please note that for every component, you will find the relevant source links in the docs:
https://www.chirpstack.io/docs/chirpstack-gateway-os/contribute.html
