### ISSUE TITLE
TLS cert generated by Chirpstack Gateway has no IP SANs

### ISSUE THREAD

**Issue by scottmil** [chirpstack/chirpstack#253]
While adding a Dragino LPS8N gateway configured with Chirpstack Gateway Bridge to a RAK7248 Chirpstack Gateway/Server, the MQTT connection fails because the web-interface generated TLS cert does not contain an IP SANs.

LPS8N log:

Wed Jul 26 15:42:55 2023 user.info chirpstack-gateway-bridge[23988]: time="2023-07-26T23:42:55.270738971Z" level=info msg="starting ChirpStack Gateway Bridge" docs="https://www.chirpstack.io/gateway-bridge/" version=4.0.10
Wed Jul 26 15:42:55 2023 user.info chirpstack-gateway-bridge[23988]: time="2023-07-26T23:42:55.281460734Z" level=info msg="backend/semtechudp: starting gateway udp listener" addr="0.0.0.0:1700"
Wed Jul 26 15:42:55 2023 user.err chirpstack-gateway-bridge[23988]: time="2023-07-26T23:42:55.767280004Z" level=error msg="[client]   x509: cannot validate certificate for 192.168.0.122 because it doesn't contain any IP SANs" module=mqtt
Wed Jul 26 15:42:55 2023 user.warn chirpstack-gateway-bridge[23988]: time="2023-07-26T23:42:55.775287815Z" level=warning msg="[client]   failed to connect to broker, trying next" module=mqtt

**Comment by brocaar** [comment]
I don't think this is a ChirpStack bug. I believe the error is about the client unable to validate the server certificate. ChirpStack does not generate server certificates, only client certificates for the gateways. If I'm not mistaking the ChirpStack Gateway Bridge tries to connect to `192.168.0.122`.

Here you find scripts to generate certificates: https://github.com/chirpstack/chirpstack-certificates.
