### ISSUE TITLE
Chirpstackv4 InfluxDB integration webpage issue

### ISSUE THREAD

**Issue by jfrankert** [chirpstack/chirpstack#254]
The issue I have is that when you are using InfluxDB2 you must select the drop down. The drop down enables the correct fill elements. Once this is complete, you would simply submit it and exit the integrations page. 

The issue occurs as follows:
1. Go back to edit the InfluxDB integration via the pencil symbol
2. The influxdb2 will be selected, but the v1 will be shown. 
3. You must select v1 then v2 to get to the right v2 template. 

This makes it confusing as to what is required.

**Comment by timmills** [comment]
Although not a bug it would be a terrific enhancement if there was some sort of sanity check done after entering the details to ensure the connection was successful.

**Comment by brocaar** [comment]
Thanks @jfrankert for reporting this issue. The above commit fixes this.

**Comment by jfrankert** [comment]
@brocaar How would I update to test the bug has been resolved?

sudo apt update
sudo apt upgrade

?

**Comment by brocaar** [comment]
This has not been released yet. I will announce the release on the forum once it is out. As well it will be in the changelog :-)

Until then, you could build the project from source for testing.
