### ISSUE TITLE
Error installing rpm package

### ISSUE THREAD

**Issue by bzuelly** [chirpstack/chirpstack#267]
I posted this in the forums and didnt get a response, so I thought Id post here.

I'm attempting to install the 4.4.3 rpm package on a fresh Rocky Linux 9.2 system.  Below is the error I'm getting. (selinux is currently disabled)  

```
chirpstack_4.4.3_linux_amd64.rpm                                                                                                                                                   2.3 MB/s |  12 MB     00:05
Error:
 Problem: conflicting requests
  - nothing provides  needed by chirpstack-4.4.3-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

I tried a few different versions and experienced the same error, however, I was able to install 4.3.2-1.  What dependencies would it be expecting?  Is there a spec file I could reference?

**Comment by brocaar** [comment]
I will look into this today or tomorrow. I can reproduce that there is an issue.

**Comment by brocaar** [comment]
I think the issue is related to:
https://github.com/cat-in-136/cargo-generate-rpm/issues/14

As there are no dependencies (`chirpstack` is a fully static binary), I will add `auto-req = "no"` to the build configuration and create a new test build.

**Comment by brocaar** [comment]
See https://github.com/chirpstack/chirpstack/commit/f39efa995f601138d06d6de694ee2c9572370ddc

This change is now building as 4.5.0-test.3 (this takes a while to compile for all targets). I'll retest once the build has finished.

**Comment by brocaar** [comment]
The above commit fixes the issue. You can download the following test RPM:

```
wget https://artifacts.chirpstack.io/downloads/chirpstack/chirpstack_4.5.0-test.3_linux_amd64.rpm
```
