### ISSUE TITLE
[BUG] Wrong view for InfluxDB integration after reloading the page (version 2)

### ISSUE THREAD

**Issue by Kampi** [chirpstack/chirpstack#271]
I have prepared an InfluxDB integration on my server. Please note the layout of the text boxes and their functions.

![image](https://github.com/chirpstack/chirpstack/assets/3458587/9e3c7fab-6f7d-4af0-bc94-017ecbd34069)

After reloading the page `InfluxDB version` is set correctly, but not the `Token` and `Organization` fields.

![image](https://github.com/chirpstack/chirpstack/assets/3458587/2f04f2d8-5507-4359-a599-e792fe95f31b)

**Comment by brocaar** [comment]
This has been fixed and the fix is already available in the latest test release:
https://www.chirpstack.io/docs/chirpstack/changelog.html#bugfixes

See also https://github.com/chirpstack/chirpstack/issues/254.
