### ISSUE TITLE
AS923 MaxPayload table error?

### ISSUE THREAD

**Issue by kelah** [chirpstack/chirpstack#276]
Hi,
After browsing some codes I notice there is inconsistency on AS923 MaxPayload table with respect to standard for DR 2 DwellTime == 0 where m & n should be 123 and 115 respectively?:

`    Revision::Latest, // PR002-1.0.0, RP002-1.0.1, RP002-1.02`
                                    `[`
                                        `(0, MaxPayloadSize { m: 59, n: 51 }),` 
                                        `(1, MaxPayloadSize { m: 59, n: 51 }),` 
                                        `(2, MaxPayloadSize { m: 59, n: 51 }),`
                                        `(3, MaxPayloadSize { m: 123, n: 115 }),`
                                        `(4, MaxPayloadSize { m: 250, n: 242 }),`
                                        `(5, MaxPayloadSize { m: 250, n: 242 }),`
                                        `(6, MaxPayloadSize { m: 250, n: 242 }),`
                                        `(7, MaxPayloadSize { m: 250, n: 242 }),`
                                    `]`

<img width="474" alt="Screenshot 2023-09-16 at 9 50 27 PM" src="https://github.com/chirpstack/chirpstack/assets/984961/2c8f0b22-ab2e-4afc-b6ad-45d2f2136c4c">

RP002-1.0.2:

**Comment by brocaar** [comment]
This might indeed have been a mistake. Would you like to create a pull-request to fix this?

**Comment by kelah** [comment]
> This might indeed have been a mistake. Would you like to create a pull-request to fix this?

ok. no problem.

**Comment by kelah** [comment]
i just did a pull request. However, I do have one question:

<img width="723" alt="Screenshot 2023-09-27 at 11 35 43 PM" src="https://github.com/chirpstack/chirpstack/assets/984961/25cc6eef-17da-47e2-9e30-673d0d49b5c9">

In the specs it says "RP002-1.0.2 Supports both LoRaWAN® 1.0.x and 1.1.x". Does this mean it shall supersede the older specs and we need to only keep the latest config/table?

**Comment by brocaar** [comment]
Before the regional parameters were tied to a LoRaWAN version, now they can be used with both LoRWAN 1.0.x and 1.1.x.

We still need to support all regional parameters revisions in ChirpStack.
