### ISSUE TITLE
chirpstack integration url being rejected by thingsboard

### ISSUE THREAD

**Issue by bzuelly** [chirpstack/chirpstack#277]
**2023-09-19 09:42:48,961 [https-jsse-nio-0.0.0.0-8080-exec-10] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "//"**

We're seeing this in the thingsboard server log.  Only seems to happen with chirpstack v4.5.0.  it doesnt happen with v3.x.  Thingsboard support says its a "default Spring Boot Firewall behavior"

We have tried to change the integration url, but removing "https://" throws a "incorrectly formatted url" error.

Chirpstack v4.5.0
Thingsboard 3.5.1

Some additional details I thought I should share.  The thingsboard integration does run through an nginx proxy.  I was able to narrow down the issue to a device within an application (with the tb integration enabled), that didn't have the ThingsboardAccessToken set.  It leaves the message below in the nginx logs (including a //)

**[19/Sep/2023:12:08:14 -0400] "POST` _/api/v1//attributes_` HTTP/1.1" 500 130 "-" "-" "-" "removedHostname" sn="removedHostname" rt=0.005 ua="ipGoesHere:8080" us="500" ut="0.006" ul="130" cs=- ct=application/json sp="TLSv1.3" sc="TLS_AES_256_GCM_SHA384" shn="-" rb="{\x22application_id\x22:\x2200000000-0000-0000-0000-000000000702\x22,\x22application_name\x22:\x22removeAppName\x22,\x22dev_eui\x22:\xdevEUI\x22,\x22device_name\x22:\x22deviceNameGoesHere\x22}" ru="`_/api/v1//attributes_`" s="https"**

After adding the token inside chirpstack, the error goes away on the thingsboard side.

Not sure if this behavior is as designed, but thought it was definitely worth mentioning.

**Comment by brocaar** [comment]
Does the integration URL you entered have a trailing `/`?

This is how the full endpoint is being generated:

```rust
        let endpoint = format!(
            "{}/api/v1/{}/attributes",
            self.server,
            vars.get("ThingsBoardAccessToken")
                .cloned()
                .unwrap_or_default()
        );
```

Adding a trailing `/` to the integration URL would then indeed create a double `//`.

**Comment by bzuelly** [comment]
no, it doesn't have a trailing slash.
to reproduce:
create an application with 4 devices.  add a ThingsboardAccessToken variable to 3 out of 4 devices.  enable the thingsboard integration.  The device without that variable causes the issue(at least in my case)

**Comment by brocaar** [comment]
I guess the only thing I could do is ignore the ThingsBoard integration for devices that do not have a `ThingsboardAccessToken` variable + print a warning in the logs. What do you think?

**Comment by bzuelly** [comment]
That sounds like a good idea.  I'm happy to test if that helps!

**Comment by brocaar** [comment]
This has been implemented in the above commit.
