### ISSUE TITLE
How to examine API interactions from the UI

### ISSUE THREAD

**Issue by lorenwest** [chirpstack/chirpstack#286]
I understand a major change in v4 was to change from REST to gRPC, which comes with some benefits but one serious drawback.

You cannot easily experiment with API traffic using the ChirpStack UI.

The API documentation is very good, but it is not perfect.  For example, it doesn't list optional parameters, ENUM values, etc.  Prior to v4 I'd open developer tools in my browser and play around the UI to fill in the holes that the documentation doesn't provide.

Is there a way to inspect the UI xhr traffic to the application server?  I see the gRPC content, but don't know how to read it.

Thank you

**Comment by lorenwest** [comment]
Here's an example.  The mechanism of specifying device-profile codecs have changed from v3 to v4.  The swagger API documentation for *POST device-profiles* shows an input element **"payloadCodecRuntime": "NONE"**.  

Version 3 API specified the element as **payloadCodec** and you'd place a value of **"CUSTOM_JS"** if you wanted to include the JavaScript codec in the POST.

Version 4 API changed that element to **payloadCodecRuntime** and the API docs don't tell you which values to use.

With ChirpStack v3 I'd open the UI in the browser, open developer tools and inspect network traffic.  Add a few device profiles with different codec types, and in a few minutes I'd have figured out the value for **payloadCodec** is **"CUSTOM_JS"**.

I'm looking for a similar process for understanding these undocumented API details using the ChirpStack UI in V4.

**Comment by bconway** [comment]
I would recommend consulting:

https://github.com/chirpstack/chirpstack/tree/master/api/proto

Those are the protobuf definitions guaranteed to be used by both the web client and the server. You could also check the generated code for a given language, as well.

**Comment by lorenwest** [comment]
Thank you for replying @bconway. This is an open source project and most open source issues can be resolved by taking the time to read the code.

But that's not quite the answer to this thread **How to examine API interactions from the UI**

A valuable mechanism for understanding API interactions was lost when moving from REST to gRPC, and I'm specifically asking if there's a mechanism out there to match or approach this functionality.

**Comment by bconway** [comment]
I think this is a good example of the [XY problem](https://en.wikipedia.org/wiki/XY_problem).

Per https://github.com/chirpstack/chirpstack/issues/286#issuecomment-1741994371, you're having trouble with the specifics of the newer gRPC API - what you're calling "undocumented API details". Your proposed solution is to change the API and/or web UI.

I have counter-proposed, and linked, a means to verify all details of the API according to the spec (protobuf definitions) used by both API and web client. No code reading was suggested.

But if there are ways to make the web UI more console-debugging-friendly, I imagine Mr. Brocaar will know.

**Comment by lorenwest** [comment]
If what you're saying is *tough luck, get over it* I can appreciate that.  Was hoping someone had a way to view active communications vs. static definitions.

**Comment by brocaar** [comment]
@lorenwest Probably it would be possible to log the UI requests to the console before making the gRPC requests by implementing an interceptor per gRPC-web client. I have not tried this, but I believe this should be possible. E.g. this could log the requests in object form to the browser console.

I understand that the move to gRPC-web might be harder to debug, but the big advantage is that most of the API code can be generated automatically + all the fields are typed using Typescript, which is a huge win in terms of development time.

I think this could help you getting started with this: https://grpc.io/blog/grpc-web-interceptor/

You would want to add an interceptor to each client, e.g.
https://github.com/chirpstack/chirpstack/blob/master/ui/src/stores/ApplicationStore.ts#L77

**Comment by lorenwest** [comment]
@brocaar Thank you for those links.  It looks like gRPC in the browser is fairly new, and one day I may be able to download a browser plugin from the web that uses the web-interceptor for further exposure of gRPC traffic.

Our use case is to interact with a small number of Chirpstack APIs to help our customers attach sensors.  We used the REST endpoints in v3, and will be using the REST service in v4.

Thank you for making the REST service available, and I hope it continues to be an option moving forward.  I have a high regard for this project, and appreciate the work you've put into it.

**Comment by lorenwest** [comment]
Closing, as it has answered the questions I had about inspecting API interactions from the browser UI.
