### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by kaaax0815** [chirpstack/chirpstack#294]
It would be nice if the chirpstack ui would support other languages

**Comment by brocaar** [comment]
Currently I'm not planning to support this. This would require a significant amount of changes at the backend (as you would like to translate error messages returned by the API as well) and the UI. The more languages would be supported, the harder it would get to make a UI change as it would require to translate the change in every language.

In most (commercial) deployments, ChirpStack is embedded in a bigger architecture and end-users never see any ChirpStack internals.
