### ISSUE TITLE
Losing parameter values in chirpstack.toml and chirpstack-gateway-bridge.toml during upgrade

### ISSUE THREAD

**Issue by IoTThinks** [chirpstack/chirpstack#295]
Hi all,
During upgrading of ChirpStack v4.x and ChirpStack Gateway Bridge v4.x, my parameter values in the chirpstack.toml and chirpstack-gateway-bridge.toml are overwritten by default values such as localhost and port 1883 (for MQTT)...

I always try to use environment parameters (such as $MQTT_SERVER and $MQTT_PORT) in the toml files.
Could we use environment parameters and parameters separately in two files? One for configuration (chirpstack.toml) and one for custom parameter values?

So it is more convenienent and less downtime during upgrading.
Thanks a lot.

**Comment by brocaar** [comment]
Let me look into this, it might be an issue in the Debian postinst script which gets triggered on installation and upgrading.

**Comment by IoTThinks** [comment]
Thanks a lot.
If this finding is fixed, it is more easy to upgrade with less downtime.

**Comment by brocaar** [comment]
The above fixes the issue. My mistake, the `postinst` is also executed post-upgrade, but with different parameters. The above commit fixes this.

**Comment by IoTThinks** [comment]
We will test this during upgrading at weekend to confirm if the issue is resolved.
Thanks a lot for your effort.
