### ISSUE TITLE
[Feature] To support responsive web on mobile

### ISSUE THREAD

**Issue by IoTThinks** [chirpstack/chirpstack#296]
Hi all,
Would Chirpstack support responsive web on mobile in the near future?
![image](https://github.com/chirpstack/chirpstack/assets/29994971/86e8c472-310f-4296-8c78-f708c58165d3)

![image](https://github.com/chirpstack/chirpstack/assets/29994971/6bce4803-995c-44b5-a695-28d2e621035e)

Thanks a lot and have a nice day.

**Comment by brocaar** [comment]
It is not on my backlog right now, but this could be a great candidate for a pull-request if you would like to work on this. The UI is built using https://ant.design/ which should support responsive layouts.

**Comment by IoTThinks** [comment]
Ok, let me try how to make it and contribute the feature.
Thanks a lot for the hint.

**Comment by brocaar** [comment]
I'm closing this issue as there hasn't been any activity on this.
