### ISSUE TITLE
Implement Java code generation for Protobuf API

### ISSUE THREAD

**Issue by brocaar** [chirpstack/chirpstack#3]
No code-generation for Java has been implemented yet. This can be ported from the github.com/brocaar/chirpstack-api  repository.

**Comment by brocaar** [comment]
I have no experience with this. If somebody could give some directions what would be the best way to implement this, contributions are more than welcome.

* https://grpc.io/docs/languages/java/basics/
* https://github.com/grpc/grpc-java/blob/master/README.md

**Comment by fmendez89** [comment]
Hi @brocaar, you mean implementing a client from the proto file?

**Comment by brocaar** [comment]
Yes, this would be the Protobuf / gRPC to Java client generation (like the Rust, Go, Python and JS clients).

**Comment by grechjoseph** [comment]
Hi @brocaar, I am experimenting with Java at the moment. I will try to contribute a Java client later. Still determining the most reliable maven plugin to use.

**Comment by sbra** [comment]
I've added Java and Kotlin code generation in this PR: https://github.com/chirpstack/chirpstack/pull/64

**Comment by brocaar** [comment]
#64 has been merged :-)
