### ISSUE TITLE
email_verified claim OIDC auth

### ISSUE THREAD

**Issue by sindreolsenhk** [chirpstack/chirpstack#302]
Hi

I am working on setting up OIDC user authentication with chirpstack 4.5. I ran into issues with the IDP (Microsoft) not providing the email_verified claim, and manually adding it makes it a string and not boolean. I was wondering if there could be implemented an automatic typecast string->bool for the case of email_verified = "true" or "false". An even better way for our case is to revive the ability to set the assume_email_verified=true in the config, as I can not find any reference to this in the v4 code. Could this be added back to the current version @brocaar ?

**Comment by sindreolsenhk** [comment]
I would greatly appreciate a `skip_email_verified=true` option returning.

**Comment by brocaar** [comment]
This has been implemented by the above commit.
