### ISSUE TITLE
Device profile selection

### ISSUE THREAD

**Issue by ccall48** [chirpstack/chirpstack#305]
The maximum amount of device profiles selectable for a tenant when adding a device to an application and selecting a device profile for the device is 10.
Can this hard limit be lifted?

**Comment by brocaar** [comment]
Maybe the widget doesn't make it obvious, but it is an auto-complete field in which you can search.

**Comment by ccall48** [comment]
Thanks brocaar.

confirmed this is the case, please close issue.
