### ISSUE TITLE
"Validation errors" when editing existing Javascript CODEC: Chirpstack v4.5.1

### ISSUE THREAD

**Issue by Dario503** [chirpstack/chirpstack#313]
What happened?

Went into an existing, working Javascript CODEC in "Device Profiles" and made a small modification. When I clicked on "Submit", the following error pops up: "Validation errors. Please inspect input fields for errors." Pulled the CODEC into VSC to check for errors, no issues. Decided to take modified codec and create a new entry in "Device Profiles"; this saves fine. Was able to reproduce this several times.

What did you expect?

For the "Submit" to happen successfully.

Steps to reproduce this issue

Steps:

1. Take an existing codec, [for example this one](https://github.com/dragino/dragino-end-node-decoder/blob/main/LSN50%20%26%20LSN50-v2/LSN50V2_v1.8.0_Decoder_ChirpstackV4.txt)
2. Create a device profile; copy this code into it. "Submit" it. this will work ok.
3. Now go into the CODEC within the Device profile just created and edit it. Add for example an else if for another fPort number.
4. "Submit" it. Validation error will occur.
5. Now create a new device profile and copy the exact same modified CODEC into it. Submit it. This will work.

Just for completeness, I do have devices using the CODEC I was editing. This has never been a problem before.

Your Environment

Raspberry Pi Linux 6.1.21-v8+

Chirpstack V 4.5.1
![image](https://github.com/chirpstack/chirpstack/assets/68450918/bc2d6326-ee26-4de7-b390-938eb653e890)

**Comment by Dario503** [comment]
Moved to "Chirpstack"

**Comment by brocaar** [comment]
One of the form tabs contains validation errors, most likely the measurements tab when you have the auto discovery of measurements enabled.
