### ISSUE TITLE
Support for JSON marshaler in ChirpStack v4

### ISSUE THREAD

**Issue by extremegf** [chirpstack/chirpstack#315]
[Docs state](https://www.chirpstack.io/docs/v3-v4-migration.html#chirpstack-gateway-bridge): 

> ChirpStack v4 supports the latest ChirpStack Gateway Bridge v3, but it does require the marshaler option to be set to protobuf (this is the default). **Support for JSON will be added** in a future ChirpStack v4 version.

It's been a while and this does not seem to be a priority. Maybe we should remove this comment from the doc?

**Comment by brocaar** [comment]
Thanks, I have removed the comment. Note that ChirpStack v4 does support JSON now :-) You can see in the logs if a gateway uses JSON or not:

https://github.com/chirpstack/chirpstack/blob/master/chirpstack/src/gateway/backend/mqtt.rs#L368

**Comment by extremegf** [comment]
That's great! Thanks.

**Comment by extremegf** [comment]
This probably is the same issue: [doc](https://www.chirpstack.io/docs/v3-v4-migration.html#chirpstack-gateway-bridge)

> ChirpStack v4 supports the latest ChirpStack Gateway Bridge v3, but **it does require the marshaler option** to be set to protobuf (this is the default).

**Comment by brocaar** [comment]
Not really, because if you are using the latest v3, you must use the Protobuf format in order to have compatibility with v4. With Protobuf (binary format) the field names do not matter, in contrast to JSON.
