### ISSUE TITLE
V4.51 - enable/disable not being properly updated until navigating away from "Applications" tab

### ISSUE THREAD

**Issue by Dario503** [chirpstack/chirpstack#319]
This has been tested and observed with Safari v17.0 and Chrome 119.0.6045.123

Steps to reproduce:

1. Using the CS browser interface (:8080) Navigate into "Applications" and then into a specific LoRaWAN device
2. Move to the "Configuration" tab
3. Disable the device.  You will be brought back to the "Dashboard" page for the device
4. Navigate back to the "Configuration" page: **_Note that the device shows as enabled_**
5. Leave it that way and go over to the Nav panel on the left and select something else like "Gateways"
6. Go back to Applications, navigate into the same device, "Configuration" and it will show it as disabled
7. Same happens when going from Disabled to Enabled, as expected.

This becomes a nuisance when disabling several devices and not being sure if they are really disabled or not. 

Attached is small video of this behavior:

https://github.com/chirpstack/chirpstack/assets/68450918/06c30069-524f-4757-9eec-6b917f0caf59

**Comment by brocaar** [comment]
Thanks for reporting @Dario503, the above commit fixes this issue.
