### ISSUE TITLE
Chirpstack compile issue - "cross: No such file or directory"

### ISSUE THREAD

**Issue by yanbozhang003** [chirpstack/chirpstack#320]
Hi,

I am trying to compile Chirpstack from source with nix.

With entering nix-shell, I execute "make dev-dependencies", from the log I can see these lines:
"cargo install cross --version 0.2.5
Updating crates.io index
Downloaded cross v0.2.5
Downloaded 1 crate (228.9 KB) in 0.59s
Installing cross v0.2.5
Updating crates.io index"

So I believe cross has been installed. 

But when executing "make debug-amd64" (under ./chirpstack subfolder), it reports error:
"cross build --target x86_64-unknown-linux-musl
make: cross: No such file or directory
make: *** [Makefile:6: debug-amd64] Error 127"

Is this caused by some path configuration error? Please help instruct how to solve. 

Many thanks.

**Comment by yanbozhang003** [comment]
I plan to find the path to cross and add it to $PATH. 

However, a simply searching finds many cross binaries, as below:
"/usr/share/icons/DMZ-White/cursors/cross
/usr/share/icons/redglass/cursors/cross
/usr/share/icons/DMZ-Black/cursors/cross
/usr/share/icons/Yaru/cursors/cross
/usr/share/icons/whiteglass/cursors/cross
/usr/share/icons/handhelds/cursors/cross
find: '/tmp/.mount_arduinAuMx8Q': Permission denied
/nix/store/hwqz0b3d0wcyjvb4fda1wf8lhj4vaa4m-source/pkgs/test/cross
/nix/store/hwqz0b3d0wcyjvb4fda1wf8lhj4vaa4m-source/pkgs/stdenv/cross
/nix/store/i1w4m7alrgg7vwgcylkycwbq7cr5rvk4-nixpkgs/nixpkgs/pkgs/test/cross
/nix/store/i1w4m7alrgg7vwgcylkycwbq7cr5rvk4-nixpkgs/nixpkgs/pkgs/stdenv/cross
/nix/store/w8lqwhvjx7q0xqpmzyi82j5ka2iqkhxf-source/pkgs/test/cross
/nix/store/w8lqwhvjx7q0xqpmzyi82j5ka2iqkhxf-source/pkgs/stdenv/cross
/nix/store/ly9xsm1yyyha1fa3phh0k3b9lw7bsnh9-cargo-cross-0.2.5/bin/cross
/snap/gtk-common-themes/1534/share/icons/Adwaita/cursors/cross
/snap/gtk-common-themes/1534/share/icons/Breeze_Snow/cursors/cross
/snap/gtk-common-themes/1534/share/icons/DMZ-Black/cursors/cross
/snap/gtk-common-themes/1534/share/icons/DMZ-White/cursors/cross
/snap/gtk-common-themes/1534/share/icons/Yaru/cursors/cross
/snap/gtk-common-themes/1534/share/icons/breeze_cursors/cursors/cross
/snap/gtk-common-themes/1534/share/icons/handhelds/cursors/cross
/snap/gtk-common-themes/1534/share/icons/redglass/cursors/cross
/snap/gtk-common-themes/1534/share/icons/whiteglass/cursors/cross
/snap/gtk-common-themes/1535/share/icons/Adwaita/cursors/cross
/snap/gtk-common-themes/1535/share/icons/Breeze_Snow/cursors/cross
/snap/gtk-common-themes/1535/share/icons/DMZ-Black/cursors/cross
/snap/gtk-common-themes/1535/share/icons/DMZ-White/cursors/cross
/snap/gtk-common-themes/1535/share/icons/Yaru/cursors/cross
/snap/gtk-common-themes/1535/share/icons/breeze_cursors/cursors/cross
/snap/gtk-common-themes/1535/share/icons/handhelds/cursors/cross
/snap/gtk-common-themes/1535/share/icons/redglass/cursors/cross
/snap/gtk-common-themes/1535/share/icons/whiteglass/cursors/cross
find: '/run/user/1000/doc': Permission denied
find: '/run/user/1000/gvfs': Permission denied
/root/chirpstack/cross
/root/.cargo/bin/cross
/root/.cargo/registry/index/index.crates.io-6f17d22bba15001f/.cache/cr/os/cross
/var/lib/docker/overlay2/1c46b04daee139d15e18d06aa2798a2ce16c9800e0b583620a231e051856a437/diff/usr/share/icons/Adwaita/cursors/cross
find: '/proc/10925/task/10925/net': Invalid argument
find: '/proc/10925/net': Invalid argument
/home/songfan/ChirpStack_source/concentratord/chirpstack-concentratord/cross
/home/songfan/ChirpStack_source/chirpstack/chirpstack/cross
/home/songfan/ChirpStack_source/mqtt-forwarder/chirpstack-mqtt-forwarder/cross
/home/songfan/.cargo/bin/cross
/home/songfan/.cargo/registry/index/index.crates.io-6f17d22bba15001f/.cache/cr/os/cross"

Please may I know which one is corret to use? (maybe "/nix/store/ly9xsm1yyyha1fa3phh0k3b9lw7bsnh9-cargo-cross-0.2.5/bin/cross"?)

**Comment by brocaar** [comment]
I'm not sure if I can help you with this, this seems to be related to your local setup and not to be an issue with the ChirpStack build commands. Note that the CI workflow is using the same commands, without the issue that you describe:

https://github.com/chirpstack/chirpstack/blob/master/.github/workflows/main.yml#L71

I'm closing this issue as I don't think this is an issue that can be solved by any code-change in this repository. If you are unable to solve it, I would recommend searching the community forum for a solution: https://forum.chirpstack.io/
