### ISSUE TITLE
Downlink repeating first message

### ISSUE THREAD

**Issue by HugoP** [chirpstack/chirpstack#321]
Good day,

Thank you for the awesome software.

Hope someone can help me with the this problem.

My configuration:
LoRaWAN v1.0.3 Class A (eu868) OTAA node making use of confirmed uplink and confirmed downlink messages.
Mikrotik wAP LR8 LoRaWAN gateway connected via ethernet and running firmware 7.12rc6

ChirpStack v4 install on bare metal PC using Ubuntu 22.04 as per https://www.chirpstack.io/docs/getting-started/debian-ubuntu.html
chirpstack 4.5.1
chirpstack-gateway-bridge version 4.0.10

I would really like to use ChirpStack v4, but can not get the downlink to work properly.

How to reproduce the issue:
Navigate to ChirpStack application device queue, click "Confirm" add hex payload and click "Enqueue" button.
![image](https://github.com/chirpstack/chirpstack/assets/20987887/dc9011d4-21c5-4f2d-b37f-c1968ecbf0b6)

Result:
Message is added to queue but gets stuck there until "Flush queue"  button is pressed.
The node receives multiple downlink messages with the same payload.
Adding messages to the queue does not get forwarded to the gateway/node and is lost after the queue is flushed.

SDR also show's that normal 15 second uplink interval is not maintained when downlink is flagged as confirmed.

Normal "confirmed" uplink messages with or without "un confirmed" downlink messages.
![image](https://github.com/chirpstack/chirpstack/assets/20987887/b32228e0-28ae-4864-942b-9b106322b89e)

When a "confirmed" downlink is queued. Interval between packets < 15 seconds.
![image](https://github.com/chirpstack/chirpstack/assets/20987887/19050994-5257-4514-96e1-e3ecfdabeda4)

The only error I can find is:
data_up: chirpstack::maccommand: Unexpected CID cid=Raw

And that only happens while there are downlink messages in the queue.

ChirpStack log's:
journalctl -f -u chirpstack

[chirpstack.log](https://github.com/chirpstack/chirpstack/files/13422517/20231121_chirpstack.log)

Events: Notice FPort:0 events while downlink is stuck in queue
![image](https://github.com/chirpstack/chirpstack/assets/20987887/1ce241b9-f71d-40a2-9116-1c13a85c0313)

LoRaWAN frames:
![image](https://github.com/chirpstack/chirpstack/assets/20987887/2ca43194-8350-44f4-b001-bdf803daf7c7)

**MQTT**
`$ mosquitto_sub -t "application/+/device/+/event/up/#" -v`
Returns JSON results

And 
`$ mosquitto_sub -t "application/+/device/+/event/down/#" -v`
Returns nothing while node receives same message as described. 

**Notes:**
- When only changing the gateway to forwarding packets to The Things Network (TTN) or LORIOT.io everything works as expected.

- I have also tried docker https://www.chirpstack.io/docs/getting-started/docker.html with the same results. Using :4 and :latest in docker-compose.yml for NS and GW made no difference.

**Comment by brocaar** [comment]
Could you please confirm your gateway is sending this packet:
https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT#L276

**Comment by HugoP** [comment]
Thank you for the reply.

Did some digging and found this
https://www.technopolis.tv/blog/2023/07/24/LoRa-Writing-our-own-Protocol-Part-2-Hardware/

Changed https://github.com/technopolistv/LoRaWAN-Python-Server/blob/main/server01.py local_port to 1702 then running it in the same host as ChirpStack and pointing my gateway to port 1702

`python3 server01.py`

Produced [LoRaWAN_UDP_Server.log](https://github.com/chirpstack/chirpstack/files/13439404/LoRaWAN_UDP_Server.log)

"Received acknowledge token" in the output indicates to me that my gateway is sending TX_ACK packets.

Is this what you were after or can you recommend another way to verify this?

**Comment by HugoP** [comment]
Ok, downlink is working.

Updated Mikrotik wAP LR8 LoRaWAN gateway to v7.13rc4

Thank you @joselunatic [issue #323](https://github.com/chirpstack/chirpstack/issues/324)
