### ISSUE TITLE
[Feature Request] - Forwarding Gateway Uplinks to Third-Party per HTTP

### ISSUE THREAD

**Issue by benchvondaranch** [chirpstack/chirpstack#322]
Hi All,

currently, the Chirpstack App allows forwarding sensor messages via "**Integrations**" to Third-Parties like IoT Platforms etc..

![2023-11-21 11_30_09-ChirpStack LoRaWAN® Network-Server](https://github.com/chirpstack/chirpstack/assets/31693685/6424c7ac-381b-4b47-8f6d-b796f3c70b61)

Additionally it would be highly beneficial if something similar could be implemented for gateways at least for HTTP.

As the gateways periodically send status updates, these updates could be used as an instrumental for monitoring and managing LoRaWAN networks. And as Monitoring sometimes happens on other platforms it would be great if these messages could be forwarded **directly** to a third-party platform, particularly via HTTP instead of requesting a status from a Third Party for example every 5 minutes.

![2023-11-21 11_46_56-ChirpStack LoRaWAN® Network-Server](https://github.com/chirpstack/chirpstack/assets/31693685/257860cf-1391-4347-98ab-c36a4d1d08f1)

I am confident that this feature could be beneficial. It would be great if you could consider this suggestion to further enhance the Chirpstack platform and integrate it more effectively into existing IoT ecosystems.

Thanks in advance and excellent work on the Chirpstack App. 
benchvondaranch

**Comment by brocaar** [comment]
> As the gateways periodically send status updates, these updates could be used as an instrumental for monitoring and managing LoRaWAN networks.

I do not think that you need any change in ChirpStack to achieve this. You could subscribe (MQTT) to `+/gateway/+/event/stats` and parse and process the received messages.

**Comment by brocaar** [comment]
I'm closing this issue for the above reason.
