### ISSUE TITLE
Editing device parameters (queue, tag, variables, ...) is buggy

### ISSUE THREAD

**Issue by Alex9779** [chirpstack/chirpstack#323]
When editing a device e.g.:

- change device attributes (name, description, ...)
- add/change tags
- add/change variables
- queue a downlink
- ...

and you "Submit" the changes you get a message pop-up "Device updated" and the dashboard of the device is displayed.
If you then go back to the page you edited something it does not show the changes/additions but the old values.
You have to leave the device details, switching to devices of the application for example and select the device again to see the changes.
Not only the jump to the dashboard is not so nice IMHO, for exmaple if you want to set mutiple downlinks, if you do not "leave" the device configuration and do other changes, the previous changes are lost.
For exmaple if you add tags, submit the changes you land on the device's dashboard, if you then go to variables and add some and submit again and then do a reload of the device, the tags you entered previously are gone.

**Comment by brocaar** [comment]
This is already fixed in https://github.com/chirpstack/chirpstack/commit/f81b868a31e72781c5b939d80434a12126915e32. This will be released soon :-)
