### ISSUE TITLE
Bug updating js CODEC

### ISSUE THREAD

**Issue by pedroinnogando** [chirpstack/chirpstack#330]
When trying to update the js codec for a device profile I constantly get this error, tried opening a new session, different browser, clearing data and cookies, the codec update cannot be submitted. This error pops: "Validation error. Please inspect input fields for errors"
The code has correct syntax.

Deleting the device profile and creating a new one results in the deletion of all devices using that device profile.

**Comment by brocaar** [comment]
This has already been fixed. You can test: https://forum.chirpstack.io/t/release-chirpstack-v4-6-test-releases/18161.
