### ISSUE TITLE
Streaming Data via Post Request not Supported by Web Application Firewall with Packet Inspection

### ISSUE THREAD

**Issue by Morpheus0x** [chirpstack/chirpstack#333]
## Background
In Chirpstack v3, the Events and LoRaWAN frames streaming was done via web socket. We recently upgraded from Chirpstack v3 to v4 which worked without any issues. However, the event streaming is Chirpstack v4 is apparently now done via a never ending post request. We are using a WAF (Web Application Firewall) to protect the Chirpstack UI and apparently the packet inspection requires the post request to finish before any data is forwarded to the client. This therefore breaks the events streaming feature in the web UI.

## The Issue
Opening the Events page for a device or the LoRaWAN frames page for a gateway or a device loads indefinitely. This is due to packet inspection which requires a request to finish before any data is forwarded to the client.

## Workaround
We investigated this issue for some time and found out that if we were using nginx as a reverse proxy (according to the config found [here](https://forum.chirpstack.io/t/lorawan-frames-come-with-5-min-delay-when-using-nginx-as-proxy/15188/3)) between Chirpstack and the WAF, after about a minute, the Events would show up and the post request to `/api.InternalService/StreamDeviceEvents` finishes with status code 200 but with the Firefox error NS_ERROR_NET_PARTIAL_TRANSFER. This was because the default nginx grpc reverse proxy read timeout to the backend server (chirpstack) is 60s. Setting this lower allows for the frames to show up faster and since the web UI opens a new post request if the old one was closed. We are using the following nginx config as a workaround for now:
```
location ^~ /api {
    grpc_read_timeout 5s;
    grpc_pass grpc://127.0.0.1:8080;
}
```
## Solution
Please look into this issue and use a different way to stream data. I know this would be hard to reproduce, since technically this error is partly due to packet inspection. However, I would argue that this is mainly an application issue since using this without a WAF and nginx as reverse proxy would cancel the post request every minute anyway and would force the web UI the create a new post request. Furthermore, streaming data via a post request isn't exactly best practice in the frontend, that's what web socket is for. The issue seems to be due to the grpc-web library used to translate the gRPC HTTP to HTTP used be the web browser. ~~I haven't looked further into if that library supports streaming via web socket, I would guess it doesn't.~~ The best solution imho would be to not use gRPC in this case and create a separate web socket api for this event streaming, like it was previously done in Chirpstack v3.

**Comment by brocaar** [comment]
> Please look into this issue and use a different way to stream data. I know this would be hard to reproduce, since technically this error is partly due to packet inspection.

You can find more details about gRPC-web here:
https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md

Wouldn't it be possible (based on headers for example) to configure your application firewall to transparently proxy the gRPC(-web) data?

**Comment by brocaar** [comment]
Please see "Server-side Streaming RPCs" :)

**Comment by Morpheus0x** [comment]
> Please see "Server-side Streaming RPCs" :)

Yes, Server-side streaming does work, but like the name says, it isn't intended to be used to communicate with a web browser, which is the case here. 

> Wouldn't it be possible (based on headers for example) to configure your application firewall to transparently proxy the gRPC(-web) data?

The WAF only forwards HTTP communication, it is used as a reverse proxy, transparent inspection must be enabled for the whole WAF which reduces the features set we require. It doesn't specifically support gRPC, which in general shouldn't be an issue using grpc-web, except when streaming data to the client, which isn't supported yet. 

According to the [roadmap for streaming](https://github.com/grpc/grpc-web/blob/master/doc/streaming-roadmap.md), they are planning to use WebTransport, but it is unclear when this will be implemented exactly. Also, WebTransport uses the HTTP/3 protocol and currently gRPC has some issues working with HTTP/2, Chirpstack for example, doesn't work if HTTP/2 is enforced.

**Comment by brocaar** [comment]
> Yes, Server-side streaming does work, but like the name says, it isn't intended to be used to communicate with a web browser, which is the case here.

Please see the definition within the gRPC context here:

> Server streaming RPCs where the client sends a request to the server and gets a stream to read a sequence of messages back. The client reads from the returned stream until there are no more messages. gRPC guarantees message ordering within an individual RPC call.

This is exactly how it is implemented within ChirpStack. The client (browser) makes a request to the server (e.g. indicating the Gateway ID or DevEUI) and gets a stream (Server > Client) that it can read.

https://grpc.io/docs/what-is-grpc/core-concepts/

---

I have been thinking about this yesterday, but I'm not planning to make implementation changes. It works well:

* Stand-alone
* With Nginx as reverse-proxy (+ grpc proxy config)
* With for example Cloudflare in front (+ grpc enabled)

I don't know which WAF service or product you are using. Maybe your WAF does not support gRPC or it needs additional configuration (note that this might also cause issues when using gRPC / not gRPC-web). Maybe you could just white-list the API parameters for which it shouldn't do deep packet inspection?

Adding a Websocket based API would mean:

* A new API interface
* Additional authentication / authorization layer
* Additional logging layer

For the sake of complexity, security, maintainability and time investment I do not think this is worth it to create an API interface parallel to what is provided by gRPC and gRPC-web.
