### ISSUE TITLE
Error running using docker compose up in step clang-wrapper-11.1.0

### ISSUE THREAD

**Issue by dwinurhadia** [chirpstack/chirpstack#336]
Hi Teams,
I try to running new chirpstack on VM Ubuntu 20.04 (running in proxmox) and i got error below

```
chirpstack-chirpstack-1  | copying path '/nix/store/a4iwnvqy7y3lmgg56wh96wsdqv6zq8rk-clang-wrapper-11.1.0' from 'https://cache.nixos.org'...
chirpstack-chirpstack-1 exited with code 0
```

Is that error about incompatibility processor/OS ?

**Comment by brocaar** [comment]
Could you please share the exact steps to reproduce the issue + some context what you are trying to achieve? Are you trying to setup the development environment or are you trying to setup a ChirpStack instance?

**Comment by dwinurhadia** [comment]
hi @brocaar 
I want to setup development environment
I'm using this tag branch `(https://github.com/chirpstack/chirpstack/releases/tag/v4.5.1)`
My goal is changing logo and etc

**Comment by brocaar** [comment]
Please share the exact steps to reproduce your issue. E.g. which commands are you executing?

**Comment by dwinurhadia** [comment]
Hi @brocaar 
here is the full command that i've do with chirpstark

`https://pastebin.com/L1wTKw4C`

Please let me know if enough

**Comment by brocaar** [comment]
The link does not work (404 error).

**Comment by dwinurhadia** [comment]
Well, 
Please check this files

[log-chirpstack.txt](https://github.com/chirpstack/chirpstack/files/13658656/log-chirpstack.txt)

I've send the full command that i've do

**Comment by brocaar** [comment]
Ah I see, I believe that is fine. The `docker compose up -d` starts all services, but the `chirpstack` service is only there to provide a development environment when you don't want to install `nix` on the host, so this immediately terminates:

https://github.com/chirpstack/chirpstack/blob/master/docker-compose.yml#L2

I don't this this is an actual issue.

**Comment by brocaar** [comment]
The two log lines are independent. Exit code `0` means success. Anything other than `0` mean error.

**Comment by dwinurhadia** [comment]
Hi @brocaar 
For now i'm able to run the command in README without an error until the process `make release-amd64`
The log show
```
[nix-shell:~/chirpstack-4.6.0/chirpstack]# ~/.cargo/bin/cross build --target x86_64-unknown-linux-musl --release
[+] Building 0.0s (0/0)                                                                                                                                                                      docker:default
ERROR: could not find cross: stat cross: no such file or directory
Error:
   0: could not run container
   1: when building custom image
   2: when building dockerfile
   3: `docker buildx build --progress auto --label 'org.cross-rs.for-cross-target=x86_64-unknown-linux-musl' --label 'org.cross-rs.runs-with=x86_64-unknown-linux-gnu' --label 'org.cross-rs.workspace_root=/root/chirpstack-4.6.0' --tag localhost/cross-rs/cross-custom-chirpstack-4.6.0:x86_64-unknown-linux-musl-adea2 --build-arg 'CROSS_DEB_ARCH=musl-linux-amd64' --build-arg 'CROSS_BASE_IMAGE=ghcr.io/cross-rs/x86_64-unknown-linux-musl:main' --file cross/Dockerfile.x86_64-unknown-linux-musl --output 'type=docker' /root/chirpstack-4.6.0` failed with exit status: 1

```

Here is the log files from my command
[19-dec-2023-err.txt](https://github.com/chirpstack/chirpstack/files/13717880/19-dec-2023-err.txt)

Is there any missing command or step from my self?

**Comment by dwinurhadia** [comment]
Finally, its works!
The issue is configuration on `export PATH="$HOME/.cargo/bin:$PATH"`

Thanks @brocaar
