### ISSUE TITLE
File api/internal/proto/internal.proto missing header for correct class tree

### ISSUE THREAD

**Issue by disk91** [chirpstack/chirpstack#348]
The protofile is missing the header to correctly generate the path for class files

option go_package = "github.com/chirpstack/chirpstack/api/go/v4/gw";
option java_package = "io.chirpstack.internal";
option java_multiple_files = true;
option java_outer_classname = "InternalProto";
option csharp_namespace = "Chirpstack.Internal";

**Comment by brocaar** [comment]
Feel free to create a pull-request if there is anything missing but please note that this is an internal Protobuf definition and it is not intended for building integrations as the methods might change any moment.
