### ISSUE TITLE
Integration payload issue with version 4.6

### ISSUE THREAD

**Issue by disk91** [chirpstack/chirpstack#349]
Hello, 

After upgrading version to 4.6, here is what I get from Chirpstack with an http intégration:
```
{"deduplicationId":"e5aa699","time":"2024-01-06T11:34:06+00:00","deviceInfo":{"tenantId":"266...09a8","tenantName":"disk91.com","applicationId":"23f92...cb5e1e","applicationName":"test app mqtt","deviceProfileId":"a4c15...c9f1966","deviceProfileName":"Default","deviceName":"mkr1300","devEui":"608...d74","tags":{}},"devAddr":"...","dr":3,"fCnt":4,"fPort":1,"data":"Fg==","confirmed":false,"adr":false,"object":{"appeui":"..."},"rxInfo":[{"gatewayId":"aaa8fd...f463","uplinkId":24261,"time":null,"rssi":-30,"snr":12.0,"context":"1UP+Hg==","metadata":{"gateway_id":"13rhZNayW2...cPC2xoioW2g8YqK","gateway_name":"beautif...ose","region_common_name":"EU868","region_name":null,"lat":0.0,"lon":0.0},"crcStatus":"CRC_OK"},
... ],"txInfo":{"frequency":867300000,"modulation":{"lora":{"bandwidth":125000,"spreadingFactor":9,"codeRate":"CR_4_5","polarizationInversion":false}}},"level":null,"code":null,"description":null,"margin":0,"batteryLevel":0.0,"queueItemId":"","acknowledged":false,"fCntDown":0,"gatewayId":null,"location":null}
```

I basically get a lot of field with null value, it's also surprising to see metadata with null value and 0 value. The time field was supposed to be renamed as an exemple but is null and no other fields is visible.

This is a raw json text dump of the received payload from chiprstack http integration.

**Comment by sp193** [comment]
Does your gateway have a GPS and does the GPS have a lock (requires line-of-sight with your sky)? If not, then I believe it's impossible for there to be a time and also coordinates under RxInfo. This same information should be shown inside Chirpstack's UI, with regards to the RxInfo section of uplink frames.

**Comment by disk91** [comment]
I think you misunderstood my issue or i was not clear: the version 4.6 has broken the integration payload.

**Comment by sp193** [comment]
I do not see anything wrong with the example you posted. You mentioned null (no time) and 0 (0 for latitude and longitude), which I understand to be linked to the GPS functionality of the LoRa gateway. If there were not what you were referring to, could you elaborate on what you meant?

I once moved up from Chirpstack 4.5 to 4.6 and noted no compatibility problems after that. If you noted a difference, one possible reason might be that backward-compatibility with Chirpstack v3 gateway bridges is no longer enabled by default, as mentioned in the release notes: https://www.chirpstack.io/docs/chirpstack/changelog.html#v460

**Comment by disk91** [comment]
Take a look at the copied payload, you may see the problem …

You can also read the link you shared where it is indicated that time has been renamed with gw_time and ns_time should have been added. 

This is true in the proto file but apparently not reported in the http integration generating a null value. 

If you look at the copied payload you will see that location are meta-data and this is not related to GPS but provided by upper layer (helium packet router). 

If I created this issue it because in version 4.4 currently running in my prod environnement all these fields are correctly filled and since I migrated staging env to 4.6.0 I got these problems prohibiting to go in prod with that version.

**Comment by disk91** [comment]
Ok .. I found the problem... my bad ...
I have an extra layer before where the payload has been catured and this layer has a format not updated correcty.
the payload from Chirpstack is ok:
```
"rxInfo":[ 
{  "gatewayId":"94bd39b8fb100467",
   "uplinkId":11039,
   "gwTime":"2024-01-07T10:59:25+00:00",
   "nsTime":"2024-01-07T10:59:25.067494722+00:00",
   ...
   "metadata":{
        "gateway_h3index":"8...65ff",
        "regi":"EU868", 
        "gateway_lat":"XX800423306070051",
        "region_common_name":"EU868", 
       "gateway_long":"XX.098059601953262",
      "region_config_id":"eu868",
      "gateway_id":"11o8R...qLG6LYf13XA",
      "gateway_name":"myt...inch"
}
```
