### ISSUE TITLE
 Feature Request : codec by fport

### ISSUE THREAD

**Issue by ric2498** [chirpstack/chirpstack#351]
The codec tab under device profile should be modified to include an option for the the payload codec.

The Payload codec should have an option by fport (default all fport)

1. an option should be added to define a codec by fport
2. the fport option should be (1 + 223) or (all) for all ports

The objective is to get a different codec by fport for one end-node; like

a) Javascript executed for the uplink data from fport 1
b) Cayenne LPP codec for the uplink data from fport 2****

**Comment by brocaar** [comment]
The `fPort` is already available to the codec, so you could create different code-paths within the codec to handle the decoding in a different way per `fPort`.

With regards to mixing JS and LPP codecs, I have never seen a device implementing two different ways of payload encoding in this way. Could you provide an example?
