### ISSUE TITLE
version 4.6.0 - can't display a device with error "Unsupported JSONB encoding version"

### ISSUE THREAD

**Issue by disk91** [chirpstack/chirpstack#352]
After migrating to version 4.6.0 of chiprstack from version 4.4.3 I'm getting the following message when trying to display a device. (going to the application, and clicking on the deviceeui to display it)

An alert message is displayed with following message: `Unsupported JSONB encoding version`
the console shows:

```
code: 13
message: "Unsupported JSONB encoding version"
metadata: 
content-length: "0"
content-type: "application/grpc-web-text+proto"
date: "Wed, 10 Jan 2024 20:41:19 GMT"
grpc-message: "Unsupported%20JSONB%20encoding%20version"
grpc-status: "13"
server: 
"nginx/1.25.3"
stack
: 
"Error: Unsupported JSONB encoding version\n    at new j (https://.../static/js/main.3719a277.js:2:1442435)\n    at Vt (https://.../static/js/main.3719a277.js:2:1466087)\n    at Et.<anonymous> (https://.../static/js/main.3719a277.js:2:1465905)\n    at qe (https://staging.helium-iot.xyz/static/js/main.3719a277.js:2:1452018)\n    at Ue (/static/js/main.3719a277.js:2:1451824)\n    at Ft (https://staging.helium-iot.xyz/static/js/main.3719a277.js:2:1459966)\n    at o.W (https://.../static/js/main.3719a277.js:2:1460986)\n    at o.R (/static/js/main.3719a277.js:2:1460965)"

``` 

The problem also seem to appear when a message arrives from network. this i breaking the communications:
```
2024-01-10T20:34:51.577917Z ERROR up{deduplication_id=f2253685-8e33-41e4-8acf-6bfc9e501514}: chirpstack::uplink::join: Handle join-request error error=Unsupported JSONB encoding version
```

**Comment by brocaar** [comment]
I can not reproduce this issue. Could you provide more context, e.g.

* OS version and PostgreSQL version?
* Did you make any manual modifications to the database?
* Could you print the schema of the `device` column?

**Comment by disk91** [comment]
Hi Orne, thank you for responding:
- OS is Ubuntu 22.04.3 LTS
- Postgres 14-alpine

I did not made any modification on the chirpstack tables structure (I add some tables into the db but don't touch the existing one)
 
```
column_name	     column_default	   data_type
join_eui		                                   bytea
application_id		                          uuid
device_profile_id		                  uuid
created_at		timestamp with time zone
updated_at		timestamp with time zone
last_seen_at		timestamp with time zone
scheduler_run_after		timestamp with time zone
skip_fcnt_check		boolean
is_disabled		boolean
tags		                                        jsonb
dev_eui		                             bytea
external_power_source		boolean
battery_level		numeric
margin		integer
dr		smallint
latitude		double precision
longitude		double precision
altitude		real
dev_addr		bytea
name		character varying
description		text
enabled_class		character
variables		character varying

```

**Comment by disk91** [comment]
OK, got it !

variables has been switch from jsonB to varchar because of springboot / hibernate new version bug preventing to correclty filter table for structure modifications. changed it back to jsonb and problem disapeared.

thank you for looking into it and confirm it was working
