### ISSUE TITLE
Bug?/chirpstack user home directory

### ISSUE THREAD

**Issue by bzuelly** [chirpstack/chirpstack#359]
when the v4 rpm is installed a "chirpstack" user is created.  Its home directory is "/etc".  Could the home directory be changed to "/etc/chirpstack" to make security scanners etc happy?

Thanks,
Bryan

**Comment by brocaar** [comment]
Isn't that already happening?

https://github.com/chirpstack/chirpstack/blob/master/chirpstack/Cargo.toml#L204
