### ISSUE TITLE
Changing device profile for an existing device has no effect

### ISSUE THREAD

**Issue by WillooWisp** [chirpstack/chirpstack#360]
I had a problem where I did not get downlinks to work, then I realized that I had selected a device profile for Class C rather than Class A for this device. But still it did not work. Looking at the events for the device presented the problem. It worked first after deleting the device and adding it with the correct profile from start. So changing profile does not seem to work.

**Up events**

Event after device profile was changed from C_EU868 to A_EU868 (CLASS_C still enabled).
time:"2024-01-30T15:09:03.955343275+00:00"
**deviceProfileId:"90750932-2f32-4d54-941f-1aef8513fc3d"
deviceProfileName:"A_EU868"**
deviceName:"Dragino LDS01"
**deviceClassEnabled:"CLASS_C"**

Event after device was removed and re-added with A_EU868 from start (now CLASS_A is enabled).
time:"2024-01-30T15:11:27.270178078+00:00"
**deviceProfileId:"90750932-2f32-4d54-941f-1aef8513fc3d"
deviceProfileName:"A_EU868"**
deviceName:"Dragino LDS01"
devEui:"a8404187818293f9"
**deviceClassEnabled:"CLASS_A"**

**Comment by brocaar** [comment]
Please note that some parameters will only have effect after re-activating the device. Some of the device-profile parameters are used as initial configuration at the activation, but then can change during the life-time of the device.

**Comment by cgh-11** [comment]
I encountered a similar issue here. I opened ClassC in the Device Profile and reactivated the device, but my device still reported as deviceClassEnable: ClasssA; The downlink also follows the ClassA method. What is the problem?, I can confirm that the device is a ClassC device. I also asked for help on the forum, but no one replied.

**Comment by WillooWisp** [comment]
I removed and readded the device, when changing class, which of course triggered an reactivation, and then it works as expected.

**Comment by cgh-11** [comment]
Boss, do you mean that you are currently running ClassA normally? May I ask what version of the image source you are using?
