### ISSUE TITLE
Multicast f_cnt out of order

### ISSUE THREAD

**Issue by TimMcGilly** [chirpstack/chirpstack#361]
I'm encountering MIC fails on data fragment messages sent via multicast from the Chirpstack FUOTA server. Looking at LoRaWAN frames for my Gateway on Chirpstack Web UI, I see that the f_cnt on messages jumps around and any time a smaller fcnt than another previous message is sent, it causes a MIC fail on STM32.

It appears to me the fcnt is set by Chirpstack FUOTA server https://github.com/chirpstack/chirpstack-fuota-server/blob/28a40c2a13af08f47d68964055236264cbc8153e/internal/fuota/fuota.go#L1323 before being enqueued and sent to Chirpstack.

Chirpstack appears to take in these queue items and asynchronous schedule all of them: https://github.com/chirpstack/chirpstack/blob/8cde64c4b70a4a78aff9f01d5dc8a1bf54b439b5/chirpstack/src/downlink/scheduler.rs#L81 I suspect it maybe is due to this, but really not that sure and have failed to be able to compile Chirpstack myself yet to verify. 

Example of LoRaWAN frames with f_cnt of 6 coming after f_cnt of 21 at end. 
![image](https://github.com/chirpstack/chirpstack/assets/11339148/672e7385-3801-4aab-a144-8979df8b911e)

I am using a STM32-WL55JC1 as the end client and Multitech MTCAP-868-001A as gateway.

**Comment by brocaar** [comment]
ChirpStack calculates a `scheduler_run_after_ts` on each enqueue, to add time margin between each downlink. This margin is based on the `multicast_class_c_margin` config value.

Did you change the `multicast_class_c_margin` configuration value?

**Comment by ferre111** [comment]
I have similar problem. Did you manage to solve it?
The only workaround I know that helped in my case is disabling the duty cycle on the gateway.

**Comment by TimMcGilly** [comment]
Not managed to solve it yet, still investigating. Interesting that disabling duty cycle fixes it. Further raised question whether issue is within chirpstack or somewhere else?

Are you using LoRa Basic Station or Semtech UDP?

**Comment by brocaar** [comment]
Please note that ChirpStack does add delays between the multicast downlinks. However, if your gateway(s) reject the downlinks because of duty-cycle restrictions, then there is a risk that multiple downlinks end up in the same batch and are handled at the same time, in which case I think you might end up with what you describe.

You might want to increase this setting to make sure the gateway will not exceeds its duty-cycle:

```
    # Multicast Class-C margin.
    #
    # This defines the minimum margin between scheduling multiple multicast downlinks
    # (within the same multicast-group). This value must be equal or greater than the
    # scheduler interval.
    multicast_class_c_margin="5s"
```

**Comment by TimMcGilly** [comment]
Thank you so much, ran a load more runs and setting `multicast_class_c_margin` above the calculated duty cycle fixes it!

I previously must have tested with a value still below the duty cycle. I still get occasional odd runs with lots of losses across all devices, however these are very rare and maybe something external in my setup so not going to worry about it.

Sorry about how long it took to test this full and get back to you
