### ISSUE TITLE
Adding additional custom Scopes via config for OIDC auth

### ISSUE THREAD

**Issue by bciotSchwarz** [chirpstack/chirpstack#365]
Hello,
 
would it be possible to implement a feature which makes it possible to request additional scopes when using OIDC Auth and make this configurable via the config?
The IDP of our organization provides additional information in a custom scope that we need for correct user role assignment and pemissions.
In our case this custom scope is called “chirpstack”.
 
I would suggest something like this under [user_authentication.openid_connect]:
additional_scopes=[“scope1”,”scope2”]

**Comment by bciotSchwarz** [comment]
We have had the same issue:
[https://github.com/chirpstack/chirpstack/issues/302](url)

**Comment by brocaar** [comment]
This could be a great addition. Would you like to create a pull-request for this?

* This is where the scopes are set: https://github.com/chirpstack/chirpstack/blob/master/chirpstack/src/api/oidc.rs#L50
* You need to look into the `User` type however (to make sure all fields are captured): https://github.com/chirpstack/chirpstack/blob/master/chirpstack/src/api/oidc.rs#L23
