### ISSUE TITLE
Azure IoT Hub/Central/DPS integration

### ISSUE THREAD

**Issue by dansiviter** [chirpstack/chirpstack#366]
Integrate into Azure IoT suite of tooling. There is a [documentation page](//github.com/chirpstack/chirpstack-docs/blob/master/src/chirpstack/backends/azure-iot-hub.md) stating 'soon' but no actual issue for this (#7 is closed). 

Ideally, in addition to IoT Hub it would be integrated into DPS and also Central to have complete end-to-end lifecycle of devices.

Although there is no 'nice' Rust APIs, there is autogenerated ReST APIs for most things:
* https://github.com/Azure/azure-sdk-for-rust/tree/main/services/svc/iotcentral
* https://github.com/Azure/azure-sdk-for-rust/tree/main/services/mgmt/iotcentral
* https://github.com/Azure/azure-sdk-for-rust/tree/main/services/mgmt/iothub

Device Provisioning Service does seem to be missing though at this time.

**Comment by brocaar** [comment]
I will remove this from the documentation. At this moment I have no plans to implement this. I know a few companies that have used the Azure IoT Hub with ChirpStack v3, but it brought them a lot of troubles. These issues were related to both the unstable SDKs and latency that the integration with IoT Hub added. Under high throughput, Azure started to throttle the ChirpStack -> Gateway messages. They had discussions with the Azure team which confirmed that the outbound throughput is limited per tier-level, the only option for these companies was to upgrade their tier (with a significant price increase) to avoid throttling of downlink payloads (and thus failed transmissions).

The companies that supported have migrated to their own MQTT broker instance with gave them better performance and a lower bill.
