### ISSUE TITLE
[Feature Request] Missing metrics reset in GUI

### ISSUE THREAD

**Issue by tompatulpan** [chirpstack/chirpstack#371]
Working with my first ChirpStack-setup I had issues with testing my devices in "Device metrics" and it would have been really good if I easily could reset my in data some where (in the GUI preferably).
Also if there was an "1h" scale would have been perfect. 

ChrirpStack is very cool, thanks for an awesome project!!

**Comment by brocaar** [comment]
I'm happy to review a pull-request for resetting metrics.

> Also if there was an "1h" scale would have been perfect.

The purpose of the metrics is to give you a high-level overview. If you need more detailed graphs, then it might be better to use for example Grafana. Note that most devices don't send data very often, so I think in general 24h should be sufficient (aggregated per hour).

**Comment by tompatulpan** [comment]
Thanks, fair enough :+1:
