### ISSUE TITLE
can not connect with the MQTT very well 

### ISSUE THREAD

**Issue by tarq2000** [chirpstack/chirpstack#372]
hello 
AfterRun the LoRaWan simulator 
I recive this codes in command :

[ Mar 3 22:14:48 ] GW[newG]: TX ACK sent

[ Mar 3 22:14:48 ] DEV[newD] |Normal| {A}: None MAC Command

[ Mar 3 22:14:48 ] DEV[newD] |Normal| {A}: Fpending unset

[ Mar 3 22:14:51 ] GW[newG]: PULL DATA send

[ Mar 3 22:14:52 ] GW[newG]: PULL ACK received

[ Mar 3 22:14:56 ] DEV[newD] |Normal| {A}: Switch channel from 2 to 1

[ Mar 3 22:14:56 ] DEV[newD] |Normal| {A}: Uplink sent

[ Mar 3 22:14:56 ] GW[newG]: PUSH DATA send

[ Mar 3 22:14:56 ] DEV[newD] |Normal| {A}: Open RXs

[ Mar 3 22:14:57 ] GW[newG]: PUSH ACK received

[ Mar 3 22:14:58 ] GW[newG]: PULL RESP received

[ Mar 3 22:14:58 ] DEV[newD] |Normal| {A}: Downlink Received

[ Mar 3 22:14:58 ] GW[newG]: TX ACK sent

[ Mar 3 22:14:58 ] DEV[newD] |Normal| {A}: None MAC Command

[ Mar 3 22:14:58 ] DEV[newD] |Normal| {A}: Fpending unset

In the MQTT explorer I just have the 
$SYS 
I do not have the EU868 and other information 
Anyone have situation like me ?
How can I improve my LoRaWan simulator ?

**Comment by brocaar** [comment]
I'm closing this issue as this does not seem to be related to ChirpStack.
