### ISSUE TITLE
Source code does not build out of the box

### ISSUE THREAD

**Issue by mrBluestSky** [chirpstack/chirpstack#375]
The code does not compile without modifying the Makefile. It uses docker-compose (which is obsolete and does not come with docker anymore) command instead of docker compose.

**Comment by bconway** [comment]
Most installations alias `docker-compose` to `docker compose` (V2), but it's possible not every OS or distribution does. Can I recommend a symlink?

**Comment by brocaar** [comment]
I think we can update the `Makefile` to `docker compose`, @mrBluestSky would you like to create a pull-request for this?

**Comment by mrBluestSky** [comment]
Created a pull request
