### ISSUE TITLE
gRPC GetMetrics "start is None" Error

### ISSUE THREAD

**Issue by DerDP** [chirpstack/chirpstack#376]
I'm trying to get a device metrics using the gRPC, but I'm getting an error:

  Error:  <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "start is None"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-03-08T12:51:17.1366875+01:00", grpc_status:13, grpc_message:"start is None"}"
>

Here is the python code that I'm testing with:

```python
from   chirpstack_api import api
import grpc
from google.protobuf.json_format import MessageToJson


server  = ""
api_token = ""


channel = grpc.secure_channel(server, grpc.ssl_channel_credentials())
client  = api.DeviceServiceStub(channel)
auth_token = [("authorization", "Bearer %s" % api_token)]


def get_device():

    try:
        req = api.GetDeviceMetricsRequest()
        req.dev_eui = '0018b20000023455'
        resp = client.GetMetrics(req, metadata=auth_token)
        print(MessageToJson(resp))
    except grpc.RpcError as e:
        print('error:',type(e))
        if e.code() == grpc.StatusCode.INTERNAL:
            print('\n  Error: ', e)
    return None


get_device()
```

Not sure if I'm missing something or not, but other endpoints are working fine.

Thank you for this great project and support!

**Comment by LiamPhil** [comment]
As the error indicates, you didn't set a start time. Unfortunately this is required for the API call.

Here's my getMetrics call as an example:
```
def getMetrics(client,token,dev_eui,start,end):
  print("Retrieving metrics from device with EUI: " + dev_eui)
  
  auth_token = [("authorization", "Bearer %s" % token)]
  try: 
    req = api.GetDeviceMetricsRequest()
    req.dev_eui = dev_eui
    req.start.FromDatetime(start)
    req.end.FromDatetime(end)
  
    resp = client.GetMetrics(req, metadata=auth_token)
  
    print(resp.metrics)
  
    return resp
```


Note that the start and end times I am passing into the function are Datetime objects. Also I've found retrieving metric through the API pretty useless unless you increase the time they are stored in the database before deleting. 

For future questions you'll probably have better luck posting them to the [Chirpstack Community Forum](https://forum.chirpstack.io/latest) then here to github
