### ISSUE TITLE
OIDC / OpenID Connect breaks after update from 4.6.0 to 4.7.0

### ISSUE THREAD

**Issue by fanuelsen** [chirpstack/chirpstack#378]
After updating to the latest version our oidc login button disappeared and was replaced with local login button. Is there some new configuration changes to OpenID Connect configuration in chirpstack? I cant see any changes to login behaviour in the change log.

**Comment by brocaar** [comment]
Please see this note: https://www.chirpstack.io/docs/chirpstack/changelog.html#notes-before-you-upgrade (this was missing in the v4.7-test.4 changelog).
