### ISSUE TITLE
Unable to authenticate using mosquitto-go-auth due to format change of password_hash in user table

### ISSUE THREAD

**Issue by IoTThinks** [chirpstack/chirpstack#38]
Hi all,
I'm testing chirpstack 4.0.0-rc.3.
And I'm doing mosquitto-go-auth at https://www.chirpstack.io/project/guides/mqtt-authentication. Yes, it works for ChirpStack Application Server v3.

In the v4, the auth_opt_hasher_iterations seems to change from 100000 to 10000.
And the table names are changed from organization to tenant and organization_user to tenant_user.
So I modified the mosquitto-go-auth as below.

```
auth_opt_hasher pbkdf2
auth_opt_hasher_salt_size 16           # salt bytes length
auth_opt_hasher_iterations 10000       # number of iterations
auth_opt_hasher_keylen 32              # key length
auth_opt_hasher_algorithm sha512       # hashing algorithm, either sha512 (default) or sha256
auth_opt_hasher_salt_encoding base64   # salt encoding, either base64 (default) or utf-8
...
auth_opt_pg_userquery select password_hash from "user" where email = $1 and is_active = true limit 1
auth_opt_pg_superquery select count(*) from "user" where email = $1 and is_admin = true
auth_opt_pg_aclquery select distinct 'application/' || a.id || '/#' from "user" u inner join tenant_user tu on tu.user_id = u.id inner join tenant t on t.id = tu.tenant_id inner join application a on a.tenant_id = t.id where u.email = $1 and $2 = $2

```
However, the format of password_hash in v4 is not compatible with mosquitto_go_auth any more.
The password_hash format in v3 works fine.
![image](https://user-images.githubusercontent.com/29994971/188792781-d2572387-0bb6-4666-ab6f-0dbf61108ff0.png)

The password_hash format in v4 is not compatible with mosquitto_go_auth
![image](https://user-images.githubusercontent.com/29994971/188792962-8837e1f8-cdb3-42de-bfb1-2ca20a282a57.png)

Mosquitto-go-auth required the password_hash format to be like this PBKDF2$sha512$100000$2WQHK5rjNN+oOT+TZAsWAw==$TDf4Y6J+9BdnjucFQ0ZUWlTwzncTjOOeE00W4Qm8lfPQyPCZACCjgfdK353jdGFwJjAf6vPAYaba9+z4GWK7Gg==

After I manually update the v4 user with v3 password_hash, mosquitto-go-auth can anthenticate with user credentials in Postgres.

Is there any workaround to change the mosquitto-go-auth to fit v4?
Or we need to set the format of password_hash in v4 back to v3 to be compatible with mosquitto-go-auth?

Thanks a lot and have a nice day.

**Comment by brocaar** [comment]
I'm sorry this no longer works. Since quite a while, ChirpStack offers a way to generate client-certificates for gateways and the (application) MQTT integration through the web-interface. For ChirpStack v4 you can find documentation here: https://www.chirpstack.io/docs/guides/mosquitto-tls-configuration.html.

The best place to handle this is probably the mosquitto-go-auth code itself. The ChirpStack v4 code uses the (new) format as defined by https://docs.rs/pbkdf2/latest/pbkdf2/.

**Comment by IoTThinks** [comment]
Thanks a lot.
Let me try your suggestion.

**Comment by IoTThinks** [comment]
To fix mosquitto-go-auth to support PHC format instead.
Closed.
