### ISSUE TITLE
API LoRAWAN codec incompatible

### ISSUE THREAD

**Issue by Watteco** [chirpstack/chirpstack#385]
API chirpstack is not compatible with the payload API LoRAWAN codec ([TS013-1.0.0 Payload Codec API 22](https://resources.lora-alliance.org/home/ts013-1-0-0-payload-codec-api))

in the code APi from lorawan the UlplinDecode is:

![image](https://github.com/chirpstack/chirpstack/assets/87481956/a83a0cca-aa85-4dcd-94da-30cadc3a33fd)

the documentation of chirpstack gives:
// Decode uplink function.
//
// Input is an object with the following fields:
// - bytes = Byte array containing the uplink payload, e.g. [255, 230, 255, 0]
// - fPort = Uplink fPort.
// - variables = Object containing the configured device variables.
//
// Output must be an object with the following fields:
// - data = Object representing the decoded payload.
function decodeUplink(input) {
return {
data: {
temp: 22.5
}
};
}

so it seems recvTime argument is not present to be compatible with API from lorawan.

**Comment by brocaar** [comment]
I believe this is only a documentation issue, the variable is there:

https://github.com/chirpstack/chirpstack/blob/master/chirpstack/src/codec/js/mod.rs#L65
