### ISSUE TITLE
 EC Private Key for generating gateway client certificates 

### ISSUE THREAD

**Issue by msoes** [chirpstack/chirpstack#386]
4.6 has supported EC private keys for generating client certificates but they are not accepted
in 4.7 anymore.
‘private_key_to_pkcs8’ in certificate.rs seems to be limited to private RSA keys as the openssl crate
is also not used anymore.

**Comment by brocaar** [comment]
What that piece of code does is converting the RSA private key from PKCS1 into PKCS8 as that is what rustls expects. If you are using an EC private key, then you can do the same using:

openssl pkcs8 -topk8 -nocrypt -in ca-key.pem -out ca-key2.pem

I'll look into if it is possible to do the auto conversion automatically like for RSA.

**Comment by brocaar** [comment]
@msoes I have been looking at this already for a couple of hours, but I'm not sure if the same can be done for EC keys. The easiest way is to use `openssl` to covert the key to PKCS8.

It seems this conversion was possible with a past version of the `sec1` crate, but I'm unable to implement this using the latest version. Please see https://github.com/RustCrypto/formats/issues/747#issuecomment-2020039170 for more information.

I would welcome any contributions on this.

**Comment by brocaar** [comment]
@msoes I have pushed the above commit. While this does not work for all EC keys, it does handle the auto-conversion for P256 EC keys, which is the most common one.

**Comment by msoes** [comment]
Thanks a lot.
