### ISSUE TITLE
Incorrect default decodeUplink and encodeDownlink

### ISSUE THREAD

**Issue by IoTThinks** [chirpstack/chirpstack#39]
The default function in Device-profile templates and Device-Profile should be modified to the below instead?
I tested the below and it works.

```
function decodeUplink(input) {
  return {
    data: {
      temp: 22.5
    }
  };
}

function encodeDownlink(input) {
  return {
    bytes: [225, 230, 255, 0]
  };
}
```
This is in the ChirpStack v4.
![image](https://user-images.githubusercontent.com/29994971/189020423-a1fcbdae-53b9-45b2-ae13-93dfcc7a1f49.png)

![image](https://user-images.githubusercontent.com/29994971/189020946-3adc6d8f-c2f6-4be1-a786-bb92c09a9fcc.png)

Thanks a lot and have a nice day.

**Comment by brocaar** [comment]
Good spot, this was already corrected in the device-profiles, but it wasn't fixed in the device-profile templates. Thanks :+1:

**Comment by IoTThinks** [comment]
Thanks a lot for your GREAT effort.

**Comment by IoTThinks** [comment]
Btw, it should be "bytes" in encodeDownlink?

[function encodeDownlink(input) {
  return {
    bytes: [225, 230, 255, 0]
  };]()
}
