### ISSUE TITLE
Alerting for inactive devices

### ISSUE THREAD

**Issue by badrbouslikhin** [chirpstack/chirpstack#390]
Hello,

I'd like to gather information about a feature I'd be happy to implement.
One thing I am missing that could significantly improve our operational efficiency and customer satisfaction is the implementation of an alerting mechanism for inactive IoT devices.

**Issue Summary:**
Currently, Chirpstack does not proactively notify us when devices, critical for monitoring building energy performance, go offline or become inactive. This lack of immediate awareness can lead to delayed reactions to potential issues, impacting our ability to maintain accurate and real-time energy performance data.

**Suggested Feature:**
I propose to develop and integrate an alerting mechanism that automatically notifies a user when an IoT device has not sent data for a predefined period. This feature would help in quickly identifying and addressing issues with inactive devices, ensuring minimal disruption to data collection and analysis.

I am not very familiar with Chirpstack's codebase yet but it shouldn't be too difficult to implement this. Inactive devices are already detected. We need to implement SMTP capabilities to support email alerting.

I'd be happy to work on this. Do you have an opinion on how should this be implemented before I start working on it?

**Comment by brocaar** [comment]
> Currently, Chirpstack does not proactively notify us when devices, critical for monitoring building energy performance, go offline or become inactive.

I don't think we should add this to ChirpStack. There are other tools that already are providing this functionality, including integrations with alerting platforms (Pushover, Pagerduty, e-mail, Slack, .....). I believe, it should be fairly easy to use ChirpStack in combination with for example Grafana and let Grafana handle the alerting part.

See also: https://grafana.com/docs/grafana/latest/alerting/

You can either use the ChirpStack database as a data-source (note that updates to ChirpStack might change the database schema), or use your own database table containing the device events as a data-source.

**Comment by badrbouslikhin** [comment]
Clear, thank you for your feedback.
