### ISSUE TITLE
Non-verbose errors from JS CODEC

### ISSUE THREAD

**Issue by pnxs** [chirpstack/chirpstack#391]
The JS Codec just returns "Exception generated by quickjs" as description.
There was a commit (0481b1a5e32101057d534774114e1baff812c9fc) but it changed nothing.

According to https://github.com/DelSkayn/rquickjs/issues/274 you need to call the catch-method on the rquickjs context to retreive detailed information.

Without any log of rquickjs it's a pain to debug any problem in the JS codec.

Tested with chirpstack 4.6.0 and 4.7.0

**Comment by pnxs** [comment]
Something like
```
        let res: rquickjs::Object = match ctx.eval_with_options(
            script,
            rquickjs::context::EvalOptions {
                strict: false,
                ..Default::default()
            },
        ).catch(ctx)
        {
            Ok(v) => v,
            Err(e) => {
                let errstr = match e {
                    CaughtError::Error(error) => error.to_string(),
                    CaughtError::Exception(ex) => ex.to_string(),
                    CaughtError::Value(value) => format!("{:?}", value),
                };
                return Err(anyhow!(
                    "{}",
                    errstr)
                );
            }
        };
```
in codec/js/mod.rs:72 would be better

**Comment by brocaar** [comment]
I'm already on it :-)

**Comment by pnxs** [comment]
Wow, that was fast. Thank you!
