### ISSUE TITLE
4.6.0 -> 4.7.0 = Postgres TLS issue

### ISSUE THREAD

**Issue by mvniekerk** [chirpstack/chirpstack#398]
Upgraded to 4.7.0 . Immediate failure:
```
Error: Error occurred while creating a new object: error performing TLS handshake: invalid peer certificate: UnknownIssuer

Caused by:
    error performing TLS handshake: invalid peer certificate: UnknownIssuer
```

DigitalOcean hosted Postgres (with SSL as required).

Postgres DSN sslmode set as "required".

**Comment by brocaar** [comment]
Have you seen this note in the changelogs:

https://www.chirpstack.io/docs/chirpstack/changelog.html#postgresql-ca-certificate

**Comment by ederuiter** [comment]
Currently the example config contains the following comments for the ssl mode options
```
  # SSL mode options:
  #  * disable - no SSL
  #  * require - Always SSL (skip verification)
  #  * verify-ca - Always SSL (verify that the certificate presented by the server was signed by a trusted CA)
  #  * verify-full - Always SSL (verify that the certification presented by the server was signed by a trusted CA and the server host name matches the one in the certificate)
 ```
However with the switch to tokio-rustls-postgres not only the supported options have changed (supported: `disable`/`prefer`/`require`, not supported: `verify-ca`/`verify-full`); but also their meaning have changed: require does not skip certificate verification anymore!; it always requires you to specify/have the correct CA certs
 
See: https://github.com/jbg/tokio-postgres-rustls/issues/11 for the discussion on this

**Comment by brocaar** [comment]
Ah good one, @ederuiter would you like to create a PR to update the configuration template? (https://github.com/chirpstack/chirpstack/blob/master/chirpstack/src/cmd/configfile.rs)
