### ISSUE TITLE
MQTT username/password credentials not working

### ISSUE THREAD

**Issue by salembream** [chirpstack/chirpstack#409]
When connecting to mosquitto broker using username/password credintials, the connection fails:

Chirpstack log:
``` 
2024-04-20T14:37:22.591903Z ERROR chirpstack::gateway::backend::mqtt: MQTT error error=Connection refused, return code: `NotAuthorized`
```

Mosquitto log:
``` 
Apr 20 17:20:33 Controller mosquitto[7885]: 1713622833: New connection from 127.0.0.1:46712 on port 1883.
Apr 20 17:20:33 Controller mosquitto[7885]: 1713622833: Sending CONNACK to 127.0.0.1 (0, 135)
Apr 20 17:20:33 Controller mosquitto[7885]: 1713622833: Client <unknown> disconnected, not authorised.
```

I am sure that the username/password are correct, and tried them from a thirdparty mqtt client (MQTT-explorer)

Please tell me if there is any further information I can provide.

if I allow anonymous connection to the broker and remove the passwd file, the connection is fine.

**Comment by brocaar** [comment]
I have tried to reproduce, but all works as expected after both configuring Mosquitto + ChirpStack with the username / password.
