### ISSUE TITLE
How to modify the content of the front-end interface？

### ISSUE THREAD

**Issue by z-lionel** [chirpstack/chirpstack#411]
When I run the chipstack/chipstack project, the project cannot access the front-end page, but there is a UI directory.
Is this project generating a chirpstack/chirpstack: 4 image?

When I run the chirpstack Docker project, I can access the front-end page, but I can't find where to modify the front-end content.

**Comment by brocaar** [comment]
The UI of ChirpStack is located here: https://github.com/chirpstack/chirpstack/tree/master/ui/src
