### ISSUE TITLE
Missing file during image packaging

### ISSUE THREAD

**Issue by z-lionel** [chirpstack/chirpstack#412]
When the Dockerfile command in the master branch is executed, the file in the target directory is missing

COPY target/x86_64-unknown-linux-musl/release/chirpstack /usr/bin/chirpstack-x86_64
COPY target/armv7-unknown-linux-musleabihf/release/chirpstack /usr/bin/chirpstack-armv7hf
COPY target/aarch64-unknown-linux-musl/release/chirpstack /usr/bin/chirpstack-aarch64

6 |     COPY target/x86_64-unknown-linux-musl/release/chirpstack /usr/bin/chirpstack-x86_64
   7 |     COPY target/armv7-unknown-linux-musleabihf/release/chirpstack /usr/bin/chirpstack-armv7hf
   8 | >>> COPY target/aarch64-unknown-linux-musl/release/chirpstack /usr/bin/chirpstack-aarch64
   9 |     
  10 |     RUN case "$TARGETPLATFORM" in \
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref c4f5b74a-a435-4d76-ba5e-39f4b6709960::r5orqtb5lerrq93g8jljdj7og: "/target/aarch64-unknown-linux-musl/release/chirpstack": not found

**Comment by brocaar** [comment]
Did you compile the binaries for all targets before generating the Docker image? If not, then this is expected. The Docker build does not compile the binaries, it only wraps exisiting binaries.

**Comment by brocaar** [comment]
I'm closing this issue as the Docker images are building fine in the CI workflow.
