### ISSUE TITLE
multicast api

### ISSUE THREAD

**Issue by Timothy-** [chirpstack/chirpstack#416]
I want to find out if a `dev_eui` belongs to a `multicast_group_id` so I can delete this mc group.

With the current grpc api I see no way to list the dev_eui (or gateways) that belong to a given `multicast_group_id`.

There is the option to perform `RemoveDeviceFromMulticastGroupRequest` and see if this returns a `StatusCode.NOT_FOUND` error, but I was hoping for a less destructive action and listing the devices/gateways seems like a good feature

**Comment by brocaar** [comment]
You can get a list of devices belonging to a multicast-group by setting `multicast_group_id`:

* https://www.chirpstack.io/docs/chirpstack/api/api.html#listdevicesrequest

The same for gateways:

* https://www.chirpstack.io/docs/chirpstack/api/api.html#api-ListGatewaysRequest
