### ISSUE TITLE
Cannot update device profile to set device_status_req_interval to 0

### ISSUE THREAD

**Issue by wouterh** [chirpstack/chirpstack#419]
Through the admin interface, I can create a device profile with `device_status_req_interval` set to 0. However, when I try to update an existing device profile to set `device_status_req_interval` to 0, I receive a validation error.

Context: I'm trying to work around the issue described here:
https://forum.chirpstack.io/t/rn2483-fw-1-0-5-hangs-after-receiving-linkadrreq-devstatusreq/9665

**Comment by brocaar** [comment]
Are you sure the validation error is related to the device-status request interval? I can not reproduce the issue. I have created:

* A device-profile with the dev-status interval set to 1: I can update this fine to 0
* A device-profile with the dev-status interval set to 0: I can update this fine to 1

**Comment by wouterh** [comment]
I tried again with a fresh device profile and I can indeed update the `device_status_req_interval` to 0.

I have some older device profiles where I cannot update it though. I'll have to investigate further what is happening there. 

Thanks for your quick response!

**Comment by wouterh** [comment]
FYI: I found the cause. The device profiles were created through the gRPC API with one of their tags set to the empty string.
Apparently that is perfectly possible through the gRPC API, but the UI marks it as invalid when trying to update the profile. I didn't notice because the error is on a different tab in the UI.
I'm updating my code to omit the tag when it's empty.
