### ISSUE TITLE
Application details and device details page are very slow

### ISSUE THREAD

**Issue by dedeweb** [chirpstack/chirpstack#42]
The page application page  (`/#/tenants/{tenantId}/applications/{applicationId}`) and device page (`/#/tenants/{tenantId}/applications/{applicationId}/devices/{deviceId)` ) are really slow (more than 30 seconds to load). 

For information, we have 700+ devices in one application. 

I looked into the http requests of the page, I think the problem may be that the request POST `/api.ApplicationService/Get` is returning too much data at once. (It returns 8.55 MB in my browser)

**Comment by IoTThinks** [comment]
May be pagination issue.
To load partially instead of full list.

**Comment by dedeweb** [comment]
Yes, I think so.

**Comment by brocaar** [comment]
Thanks for reporting. I'll look into this today.

**Comment by lawrencedudley** [comment]
We've got an application with a similar number of devices in and have no performance issues with it.

I reckon this could be an issue with your setup - what hardware are you running this on?

**Comment by dedeweb** [comment]
Here are the HTTP requests on my chirpstack ? 
![image](https://user-images.githubusercontent.com/23235119/193211973-cca196d0-9ffa-49aa-93b1-5ebe01aace9c.png)

What can I do to help you solve this bug ? Do you need some logs? For information, the devices are from a migration from chirpstack v3...

**Comment by dedeweb** [comment]
No, descriptions are at most a few word long, and we don't use any tags at all... 
Something weird is happening, because event for a 9MB request, 50 seconds is veeeery long

**Comment by brocaar** [comment]
This is odd and is not a pagination issue. Note that your issue occurs on the get of the application. This is the response:
https://github.com/chirpstack/chirpstack/blob/master/api/proto/api/application.proto#L434

```proto
message GetApplicationResponse {
    // Application object.
    Application application = 1;

    // Created at timestamp.
    google.protobuf.Timestamp created_at = 2;

    // Last update timestamp.
    google.protobuf.Timestamp updated_at = 3;

    // Measurement keys.
    // This contains the measurement keys from all the device-profiles that
    // are used by the devices under this application.
    repeated string measurement_keys = 4;
}
```

Which contains the following `Application` message:

```proto
message Application {
    // Application ID (UUID).
    // Note: on create this will be automatically generated.
    string id = 1;

    // Application name.
    string name = 2;

    // Application description.
    string description = 3;

    // Tenant ID (UUID).
    string tenant_id = 4;
}
```

The only thing that could make the response very large is many `measurement_keys`. Note that this field contains the sum of all measurements configured under the device-profiles that are used by the devices under your application.

**Comment by dedeweb** [comment]
Ok, I think I know what happened here : we have a decoder wich returns an array of events (with an unique ID on each event). I think chirpstack tried to create a measurement for each event on every device we have :/

**Comment by brocaar** [comment]
Maybe the auto-detect of measurements should be turned into an option? By default it would be enabled (so nothing changes), but in your case you probably want to disable this feature.

**Comment by dedeweb** [comment]
Or maybe just putting a max limit on the number of measurements is enough ? (like a hundred or so ?)
In our case, I'm not sure we would have thought of disabling the feature before... Now we have hundred of thousands of measurements, we can't do anything on device profile edition : the web page is not responding anymore...

**Comment by brocaar** [comment]
@dedeweb the max. limit would be more of a workaround. As the payload keys are random, there isn't really a need to turn these into measurements in the first place. The above commit makes it possible to enable/disable the auto-detect. In your case I would recommend disabling this feature + updating the `device_profile` table by hand to empty the `measurements` column.

**Comment by dedeweb** [comment]
Thanks for the tip and for the fix ! :-)
