### ISSUE TITLE
Python example (downlink_enqueue.py) fails with chirpstack-api 4.8.1

### ISSUE THREAD

**Issue by hruotsalainen** [chirpstack/chirpstack#422]
After following the installation steps of chirpstack-api (4.8.1) for Python and running the given example code, the
following error message appears:
`ModuleNotFoundError: No module named 'chirpstack_api.api.frame_log_pb2'`

After downgrading the api to version 4.8.0 the example works as expected.

OS: 5.15.146.1-microsoft-standard-WSL2
Python: 3.10.12
Pip: 22.0.2

**Comment by dokzlo13** [comment]
Hi, also facing this issue.

Seems like `frame_log` proto files was removed at all from [proto/api](https://github.com/chirpstack/chirpstack/tree/ae31e4d85f6f5e86aeb2cebcdbba3a016d2efe02/api/proto/api). And after automatic python stubs generation from *.proto files using we don't have `frame_log_pb2.py` anymore, but `__init__.py` still references these files, causing an import error:

https://github.com/chirpstack/chirpstack/blob/ae31e4d85f6f5e86aeb2cebcdbba3a016d2efe02/api/python/src/chirpstack_api/api/__init__.py#L9-L10

**Comment by brocaar** [comment]
Good catch @dokzlo13, this protobuf file was removed already in earlier releases, but because in the past Python files were committed in the git repo, the generated Python file was not automatically removed.

**Comment by brocaar** [comment]
I have pushed a `4.8.1.post1` Python package, that should resolve the import issue. Could you please re-test against that version?

**Comment by dokzlo13** [comment]
It looks like there are no import errors in version 4.8.1.post1 anymore. Thanks for the quick fix!
