### ISSUE TITLE
OIDC certificate error with custom CA since rustls

### ISSUE THREAD

**Issue by pyttel** [chirpstack/chirpstack#423]
We are using ChirpStack in a Kubernetes cluster with OIDC in place. Since version 4.7.0 we have an exception with OICD. The IDP login results in following backend exception:

```
2024-05-14T13:36:02.572418Z ERROR http{method="GET" uri=/auth/oidc/login version=HTTP/1.1}: chirpstack::api::oidc: Get OIDC client error error=Request failed: request failed: error sending request for url (…/.well-known/openid-configuration): error trying to connect: invalid peer certificate: UnknownIssuer: error trying to connect: invalid peer certificate: UnknownIssuer: invalid peer certificate: UnknownIssuer
2024-05-14T13:36:02.572444Z INFO http{method="GET" uri=/auth/oidc/login version=HTTP/1.1}: chirpstack::api: Finished processing request status="500" latency=13.379215ms

```

After some analysis I maybe found the reason. In [oidc.rs](https://github.com/chirpstack/chirpstack/blob/master/chirpstack/src/api/oidc.rs) `async_http_client` of [reqwest.rs](https://github.com/ramosbugs/oauth2-rs/blob/4.4.2/src/reqwest.rs) of oauth2 is used. This uses `reqwest::Client::builder()` from reqwest. But for custom certificates shouldn’t it be `reqwest::Client::builder().use_rustls_tls()`? This would cause the need of custom implementation of `async_http_client`.

`SSL_CERT_FILE` environment variable is set to valid a certificate mounted into the container (used for postgres connection and checked with openSSL).

This project is my first touch with Rust. I come from the Java community. So please be lenient if I misunderstood something^^

In addition I already implemented additional scope feature for OIDC and oAuth. After our internal tests I would like to make a pull request for this feature 😊

**Comment by brocaar** [comment]
Custom / self-signed CA certificates / CA certificates not trusted by the host system were never intentionally supported for HTTP requests (OIDC, OAuth2, HTTP integrations, .....) unless there is an explicit `ca_cert` option in the ChirpStack configuration (like for the Backend Interfaces).

Maybe this used to work in the past using `SSL_CERT_FILE`, but that is not a (documented) ChirpStack feature.

**Comment by pyttel** [comment]
Hi,
so we have the CA certificate integrated to the host system, but it is not recognized by the async http client of oAuth lib. I wanted to reimplement the `async_http_client` method of oauth lib to load certificated provided by the config. But I run into version conflicts of reqwest dependency. 

The main difference I would like to integrate is the part from Backend client:

 ```rust
pub async fn int_async_http_client(
    request: HttpRequest,
) -> std::result::Result<HttpResponse, oauth2::reqwest::Error<reqwest::Error>> {
    let conf = config::get();
    let mut client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(5))
        .use_rustls_tls();

    if !conf.user_authentication.openid_connect.tls_cert.is_empty() && !conf.user_authentication.openid_connect.tls_key.is_empty() {
        trace!(tls_cert = %conf.user_authentication.openid_connect.tls_cert, tls_key = %conf.user_authentication.openid_connect.tls_key, "Reading client certificate");

        let mut b: Vec<u8> = Vec::new();
        File::open(&conf.user_authentication.openid_connect.tls_key)
            .context("Open tls_key")?
            .read_to_end(&mut b)
            .context("Read tls_key")?;
        File::open(&conf.user_authentication.openid_connect.tls_cert)
            .context("Open tls_cert")?
            .read_to_end(&mut b)
            .context("Read tls_cert")?;

        trace!("Parsing client certificate");
        let id = Identity::from_pem(&b).context("Parse tls_cert and tls_key")?;

        trace!("Adding client certificate as identity");
        client = client.identity(id);
    } else {
        trace!("No client certificate configured");
    }

    if !conf.user_authentication.openid_connect.ca_cert.is_empty() {
        trace!(ca_cert = %conf.user_authentication.openid_connect.ca_cert, "Reading CA certificate");
        let mut b: Vec<u8> = Vec::new();
        File::open(&conf.user_authentication.openid_connect.ca_cert)
            .context("Open ca_cert")?
            .read_to_end(&mut b)
            .context("Read ca_cert")?;

        trace!("Parsing CA certificate");
        let cert = Certificate::from_pem(&b).context("Parse ca_cert")?;

        trace!("Adding CA certificate to root certificate bundle");
        client = client.add_root_certificate(cert);
    } else {
        trace!("No CA certificate configured");
    }

    let c = client.build().map_err(Error::Reqwest)?;
    let mut request_builder = c.request(request.method, request.url.as_str())
        .body(request.body);
    for (name, value) in &request.headers {
        request_builder = request_builder.header(name.as_str(), value.as_bytes());
    }
    let request = request_builder.build().map_err(oauth2::reqwest::Error::Reqwest)?;

    let response = c.execute(request).await.map_err(oauth2::reqwest::Error::Reqwest)?;

    let status_code = response.status();
    let headers = response.headers().to_owned();
    let chunks = response.bytes().await.map_err(oauth2::reqwest::Error::Reqwest)?;
    Ok(HttpResponse {
        status_code,
        headers,
        body: chunks.to_vec(),
    })
}
```

As I said before I’m not a Rust specialist and I would think about a more general solution for all http clients.

Would you support us to develop a solution? Or maybe I can get a hint to solve the problem.

BR
Tobi

**Comment by brocaar** [comment]
Could you let me know which OIDC provider you are trying to integrate with?

I'm not sure if I fully understand if your code is trying to fix the issue that you are reporting:

> invalid peer certificate: UnknownIssuer

I believe this indicates that the client (ChirpStack) is unable to verify the CA that signed the server-certificate of the OIDC provider.

However, it looks that your code is implementing also a client-certificate (`tls_cert`, `tls_key` config options). This has nothing to do with validating the CA that signed the server-certificate.

---

If possible, I would like to avoid adding a `ca_cert` config option (or any other TLS related config) to the OIDC integration.

**Comment by rekcaiot** [comment]
Hi,
I am working together with @pyttel on this topic.
We have also tried to put the certificates into the /etc/ssl/certs/ directory without success.

As I understand the issue at the moment the only certs that are trusted are the ones from Mozilla:
https://github.com/rustls/webpki-roots

The main problem in our case is that we have our own PKI in our company. 
This root ca cert of course is not part of the Mozilla roots.
And our authentication endpoint presents us this certificate.

**Comment by brocaar** [comment]
I think I see what the issue is, ChirpStack itself uses:

```toml
reqwest = { version = "0.12", features = [
	"json",
	"rustls-tls-native-roots",
], default-features = false }
```

However, `openidconnect` depends (through `oauth2`) on `reqwest=0.11`, thus the `rustls-tls-native-roots` is not applied I believe.

It looks like the next `openidconnect` version will be updated to `reqwest=0.12` which means that the above feature-flag will be applied to the `reqwest` client used. I would prefer this path over implementing a custom HTTP client.

**Comment by pyttel** [comment]
>  I would prefer this path over implementing a custom HTTP client.
Thanks for the effort! Yes I would also prefer to wait for the update.

**Comment by brocaar** [comment]
@pyttel the above commit should fix the issue.

**Comment by mgruenberger21** [comment]
Hello,
is it possible to bypass this issue?
Import CA somewhere in chirpstack?
We want to use our own CA für openid-connect.

Kind regards
