### ISSUE TITLE
import-legacy-lorawan-devices-repository: Unexpected region AS923-2

### ISSUE THREAD

**Issue by Dennis14e** [chirpstack/chirpstack#426]
Hello,

Within the chirpstack container I have mounted the directory `/opt/lorawan-devices`, which contains the Git repository https://github.com/TheThingsNetwork/lorawan-devices.
When executing the command `chirpstack -c /etc/chirpstack import-legacy-lorawan-devices-repository -d /opt/lorawan-devices` I get the following error after a while:
```
thread 'main' panicked at chirpstack/src/main.rs:119:18:
called `Result::unwrap()` on an `Err` value: Unexpected region: AS923-2
```

Is this correct? Looks like a valid region to me.

**Comment by brocaar** [comment]
You should not have any issues importing https://github.com/brocaar/lorawan-devices, which is the last revision before TTN changed the license of this repository. Unfortunately, the license of the latest lorawan-devices does not allow you to mass-import this repository.
