### ISSUE TITLE
Chirpstack-gateway-bridge, gateway 16 channels (basic station, SX1302, SX1303)

### ISSUE THREAD

**Issue by BlokhinVega** [chirpstack/chirpstack#428]
Hi all!

Does chirpstack-gateway-bridge support the ability to connect Gateways built on the reference SX1302, SX1303?

The example configuration file itself says that it is intended for the SX1301.

Currently testing a Gateway prototype with two SPI LoRa modules: 8 + 8 channels

I want to connect the gateway to the server as one 16-channel device, and not as two 8-channel devices..

Has anyone experienced this possibility?

**Comment by brocaar** [comment]
https://github.com/chirpstack/chirpstack-gateway-bridge/issues/237
