### ISSUE TITLE
Missing revision in Device profiles

### ISSUE THREAD

**Issue by VladislavGatsenko** [chirpstack/chirpstack#429]
The new "Regional parameters revision" : RP002-1.0.4 is not displayed on the Device Profile page:

<img width="1655" alt="00001" src="https://github.com/chirpstack/chirpstack/assets/85576481/85832d0b-3117-430a-9319-e9b5d9dbdece">
<img width="1655" alt="00002" src="https://github.com/chirpstack/chirpstack/assets/85576481/6be3ef91-d86c-47e3-948d-53b3f059f028">
<img width="1655" alt="00003" src="https://github.com/chirpstack/chirpstack/assets/85576481/b2560bda-7e8f-4035-8d39-aed65ac997c4">

**Comment by IoTThinks** [comment]
I'm about to create the same issue.
Yes, I have the same issue.
