### ISSUE TITLE
Integration output discards key from JSON object if value is 0 or null

### ISSUE THREAD

**Issue by mmrein** [chirpstack/chirpstack#43]
Tested with MQTT intergation on `application/+/device/+/event/up`. When `data: null`, but also `dr: 0` or `fCnt: 0`, the respective key is not present in the JSON object at all.

**Comment by IoTThinks** [comment]
I confirmed the same issue. 
For the first uplink fCnt will be 0 and not in the JSON.

First uplink
`{"deduplicationId":"xxxxxx18-6ec9-4a68-8e26-5c608a408eff","time":"2022-09-23T02:02:06.744554+00:00","deviceInfo":{"tenantId":"xxxxxxd4-c6f1-4fbd-8f87-4025e1d49242","tenantName":"xxxxxxxx","applicationId":"xxxxxx18-01d8-44ed-ba31-67d0b53456e1","applicationName":"Applications with RS485 support","deviceProfileId":"xxxxxx12-9c3d-466c-820a-8dbce2bc7272","deviceProfileName":"RS485_LN","deviceName":"RS485_LN","devEui":"XXXXXXc161832b12"},"devAddr":"00e5e007","adr":true,"fPort":2,"data":"AQEwAAAAAAAIdgAAAAO0+gAB4gg=","rxInfo":[{"gatewayId":"xxxxxx20e2e84150","uplinkId":48620,"time":"2022-09-23T02:02:06.744554+00:00","rssi":-19,"snr":10.0,"location":{"latitude":110.77143,"longitude":1016.65851,"altitude":10.0},"context":"AQHIfA==","metadata":{"region_common_name":"AS923_2","region_name":"as923_2"}}],"txInfo":{"frequency":921400000,"modulation":{"lora":{"bandwidth":125000,"spreadingFactor":12,"codeRate":"CR_4_5"}}}}`

Second uplink
{"deduplicationId":"xxxxxx39-a0c4-45dc-8f17-3c89a9002692","time":"2022-09-23T02:03:06.907817+00:00","deviceInfo":{"tenantId":"xxxxxxd4-c6f1-4fbd-8f87-4025e1d49242","tenantName":"EasyLoRa","applicationId":"xxxxxx18-01d8-44ed-ba31-67d0b53456e1","applicationName":"Applications with RS485 support","deviceProfileId":"xxxxxx12-9c3d-466c-820a-8dbce2bc7272","deviceProfileName":"RS485_LN","deviceName":"RS485_LN","devEui":"xxxxxxc161832b12"},"devAddr":"00e5e007","adr":true,**"fCnt":1**,"fPort":2,"data":"AQEvAAAAAAAIfQAAAAO0+gAB4gg=","rxInfo":[{"gatewayId":"xxxxxx20e2e84150","uplinkId":51058,"time":"2022-09-23T02:03:06.907817+00:00","rssi":-17,"snr":10.5,"location":{"latitude":110.77143,"longitude":1016.65851,"altitude":10.0},"context":"BJfP/A==","metadata":{"region_name":"as923_2","region_common_name":"AS923_2"}}],"txInfo":{"frequency":921400000,"modulation":{"lora":{"bandwidth":125000,"spreadingFactor":12,"codeRate":"CR_4_5"}}}}

**Comment by mmrein** [comment]
Well, this is example of message which has both dr and fcnt equal to 0 and also null data. Those key-value pairs are simply not present in structure. Note that `"object":{"data":null}` is present as output of decoder function if `( input.bytes.length <= 0 )`

```json
{"deduplicationId":"9f6009c9-8f86-4635-b192-f3636bd657a7","time":"2022-11-08T08:09:20.057185346+00:00",
"deviceInfo":{"tenantId":"00000000-0000-0000-0000-000000000002","tenantName":"A-Name",
"applicationId":"00000000-0000-0000-0000-000000000001","applicationName":"App-Name",
"deviceProfileId":"32794dc0-c2c9-4d84-acd7-903a5c70370f","deviceProfileName":"Device-Profile-Name-OTAA",
"deviceName":"Device-Name-01","devEui":"0102030405060708"},
"devAddr":"039168f4","adr":true,"object":{"data":null},
"rxInfo":[{"gatewayId":"fcc23dfffexxxxxx","uplinkId":1805976519,"time":"2022-11-08T08:09:20.057185346+00:00",
"rssi":-99,"snr":7.5,"channel":7,"location":{"latitude":1.0,"longitude":1.0},"context":"O9eg3A==",
"metadata":{"region_common_name":"EU868","region_name":"eu868"}}],
"txInfo":{"frequency":867900000,"modulation":{"lora":{"bandwidth":125000,"spreadingFactor":12,"codeRate":"CR_4_5"}}}}
```

**Comment by mmrein** [comment]
Solved by https://github.com/chirpstack/chirpstack/pull/63

Side note, just for reference: packet with no data is now empty string `"data":""` instead of empty value `"data":null` like it was in Chirpstack V3.
