### ISSUE TITLE
Off-Topic: NB-IoT

### ISSUE THREAD

**Issue by offizium-berndstorath** [chirpstack/chirpstack#435]
What are your thoughts on NB-IoT?
Its getting more popular and because Chirpstack already has a good System with decoders and device registration, why not extend it to support NB-IoT?

**Comment by brocaar** [comment]
I don't think it makes sense to extend ChirpStack to support NB-IoT. ChirpStack is a LoRaWAN Network Server which enables you to setup and operate your own LoRaWAN network. With NB-IoT you are dependent on a network provider providing you with NB-IoT coverage (which will handle the MAC layer and provide you with the API for sending and receiving data). It makes more sense at the application-server level (different service), which receives data from ChirpStack and the NB-IoT provider of your choice or any other technology.
