### ISSUE TITLE
[Feature Request] Config option to use different tile server

### ISSUE THREAD

**Issue by physec-rex** [chirpstack/chirpstack#437]
It would be nice to be able to overwrite the default Tileserver URL with a configuration value. This would allow us to use a self hosted tile server with the following benefits:

- We can load a map in networks where outgoing requests are restricted.
- We can modify the theme of the tiles
- We do not need to put load on the openstreetmap tileserver and follow the recommendation of their tile usage policy regarding hard-coding their tile url: https://operations.osmfoundation.org/policies/tiles/

**Comment by brocaar** [comment]
I'm happy to review a PR to make this configurable. I think it would be best to add the URL to the tileserver here in the API:
https://github.com/chirpstack/chirpstack/blob/master/api/proto/api/internal.proto#L220
