### ISSUE TITLE
Events or the LoRaWAN frames tabs empty on Mac

### ISSUE THREAD

**Issue by wasalm** [chirpstack/chirpstack#44]
When I open the "Events" or the "LoRaWAN frames" tab in the online interface, no data will be shown for the first 4 minutes. 
The chrome inspector shows that for the post requests of `StreamDeviceEvents` and `StreamGatewayFrames` does not return anything for the first 4 minutes.

According to the console log
```
DEBUG gRPC{uri=/api.InternalService/StreamGatewayFrames}: chirpstack::api: Started processing request
Sep 26 23:58:12.893  INFO gRPC{uri=/api.InternalService/StreamGatewayFrames}: chirpstack::api: Finished processing request status="200" latency=12.940832ms
```
these endpoints should have returned something.

I know for sure that data is parsed and received, because I see messages on mqtt. Also the link metrics are updated.

Setup:
- latest chirpstack using docker
- udp-packet-forwarder as gateway (docker, rakwireless/udp-packet-forwarder:latest)

Thanks for the help
![Schermafbeelding 2022-09-27 om 00 36 03](https://user-images.githubusercontent.com/4749597/192402756-fb8f5488-f347-48db-84a7-5c0f3ed377ff.png)
<img width="1440" alt="Schermafbeelding 2022-09-27 om 01 01 53" src="https://user-images.githubusercontent.com/4749597/192402783-46cb3fd1-d0e9-4aa3-9831-a1eff3ac4ce9.png">

N.B. in the image, "Wachten" means "Wait/Delay"

**Comment by brocaar** [comment]
Are you using a proxy in front of ChirpStack (e.g. NGINX)?

**Comment by wasalm** [comment]
No. I'm not.I'm running it in docker containers on a raspberry pi.Op 27 sep. 2022 08:54 schreef Orne Brocaar ***@***.***>:
Are you using a proxy in front of ChirpStack (e.g. NGINX)?

**Comment by sagar-patel-sls** [comment]
@brocaar 

I'm also facing the same issue. The inspector shows that the post requests of `StreamDeviceEvents` and `StreamGatewayFrames `does not return anything and the request shows `pending`.

Chirpstack running on docker containers on Ubuntu Machine

![image](https://user-images.githubusercontent.com/43664335/192486804-a8e55201-46f8-453d-bc03-cbfea577a2fd.png)

**Comment by brocaar** [comment]
I think there are two topics:

### The StreamDeviceEvents and StreamGatewayFrames do not terminate

This is normal, because these are streaming endpoints. As long as you keep your browser tab open, it keeps the connection to the server open as it needs to receive data :-) You might see in the server logs that the API has returned, I think what you are seeing is that it returned a response on the incoming request, but it doesn't mean the connection was closed.

### You expect data, but you do not see any

1) Your gateway receives data (which you can confirm on the MQTT topics), but you don't see it in the LoRaWAN frames tab of the gateway
2) You expect an uplink in the LoRaWAN frames tab, but you don't see anything
3) You  expect an uplink event in the events tab (of the device), but you don't see anything (but you do see events coming in on the MQTT application/...../event/up topic)


Is this the case?

**Comment by sagar-patel-sls** [comment]
@brocaar 

yes, I'm receiving data on the MQTT `application/...../event/up` topic but don't see anything on the LoRaWAN frames tab or device event tab.

**Comment by wasalm** [comment]
Yes this is the case for me.
As a test I used one of my LoRa devices to send some demo data.
Hereby are the logs of the chirpstack app. 
(` sudo docker logs chirpstack-docker_chirpstack_1 -f > chirpstack-logs.txt`)
[chirpstack-logs.txt](https://github.com/chirpstack/chirpstack/files/9654704/chirpstack-logs.txt)

Also I give a copy of the communication on mqtt 
(`sudo docker exec chirpstack-docker_mosquitto_1 mosquitto_sub -t '#' -v > mqtt-logs.txt`)
[mqtt-logs.txt](https://github.com/chirpstack/chirpstack/files/9654705/mqtt-logs.txt)

During that time no data was received in the web ui. Neither in Firefox nor Chrome.
I noticed that when I restarted chirpstack all the data is flushed to the client.
It sounds like there is some issue with caching.
This is weird as I use the standard installation described in https://www.chirpstack.io/docs/getting-started/docker.html

**Comment by brocaar** [comment]
When I use the chirpstack-docker example, and go to the LoRaWAN frames tab of the gateway, I see the data in realtime without any significant delay....

How does your Docker setup look like and what is your host OS?

**Comment by wasalm** [comment]
I use docker on a Rock Pi 4 (Raspberry Pi clone).
I also tested the issue on a Raspberry Pi B+, using the chirpstack-gateway-os-full image.
In both cases I don't see any data.
As consentrator I use https://uk.pi-supply.com/products/nebra-sx1301-lora-concentrator, which is a similar layout as https://uk.pi-supply.com/products/iot-lora-gateway-hat-for-raspberry-pi.

Do you have a (node-js) script which simulates a gateway so we can test if the issue in this.
I have this issue in chrome, firefox and Safari. (Using a Macbook pro)

**Comment by wasalm** [comment]
Found the source: It doesn't work on Mac, but it works on Android and Windows.

**Comment by wasalm** [comment]
Found the issue. It turns out that grpc streams are not yet capatible with web. 
See for example footnote 20 in https://grpc.io/blog/state-of-grpc-web/
This issue is explained in https://github.com/grpc/grpc-web/issues/344:

> The problem there is the binary format - currently the XHR API does not return back partial chunked response if the response body is binary. Hence the current default mode for gRPC-Web is `grpcwebtext` (or basically `application/grpc-web-text`). This is somewhat covered in this old issue https://github.com/grpc/grpc-web/issues/87.

I suggest in order to mitigate this issue, change from grpc-web to grpc-web-text

**Comment by wasalm** [comment]
Found the real culprit: Sophos antivirus/firewall.
Issue is described in https://github.com/grpc/grpc-web/issues/1245

**Comment by sagar-patel-sls** [comment]
> Found the real culprit: Sophos antivirus/firewall. Issue is described in [grpc/grpc-web#1245](https://github.com/grpc/grpc-web/issues/1245)

Hi @wasalm 

can you please let me know what configuration done at sophos/antivirus or firewall 

i'm facing same issue with sophos

**Comment by wasalm** [comment]
I went to cloud.sophos.com and disabled web protection
