### ISSUE TITLE
[Feature Request] Improve QuickJS Error Verbosity During JS Evaluation + Typo Correction

### ISSUE THREAD

**Issue by rgarmyn** [chirpstack/chirpstack#440]
Issue #391 resolved JavaScript exceptions during payload decoding. However, in certain scenarios, a generic QuickJS exception is still thrown:
 `Evalulate script. Exception generated by QuickJS`. 
This occurs when an error arises during the evaluation of the JavaScript module, before the evaluation of the JavaScript script itself:
`let (buff, buff_promise) = buff.eval().context("Evalulate script")?;`
Reference to the [code](https://github.com/chirpstack/chirpstack/blob/38d544a5f7b5e4fad61328ed3e7af2882fb5d9a2/chirpstack/src/codec/js/mod.rs#L61C1-L64C60)

Would it make sense to add also a catch() method to help debugging further? For now I get this generic Quickjs exception for certain payloads which makes it difficult to find the cause of the exception.

Additionally, there's a minor typo in the context message. It should be "Evaluate script" instead of "Evalulate script".

**Comment by brocaar** [comment]
Hi @rgarmyn, would you like to create a PR for the above changes?

**Comment by brocaar** [comment]
@rgarmyn I experienced the same issue when reviewing some code changes. In some cases (I assume based on load / running concurrent tests) the JS codec tests would fail. The above commit fixes this.

**Comment by rgarmyn** [comment]
Thank you!
