### ISSUE TITLE
How to commit new feature and create pull request?

### ISSUE THREAD

**Issue by pyttel** [chirpstack/chirpstack#444]
I have implemented a feature to configure additional scopes for OAuth2 and OIDC over configuration. Currently only “email” and “profile” are requested. I would like to commit my changes and create a pull request. Currently I’m not able to push my code to new branch. What is the workflow to do so?

BR Tobi

**Comment by brocaar** [comment]
The process would be:

* Fork the `chipstack` repository
* Push your local branch with changes to your own `chirpstack` fork
* Then through the GitHub web-interface you can create a pull-request

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
