### ISSUE TITLE
gRPC API requires serving and forward integrity key to activate LoRaWAN 1.0.3 ABP device

### ISSUE THREAD

**Issue by tuialexandre** [chirpstack/chirpstack#446]
When activating a device through the gRPC API it is required to supply both `s_nwk_s_int_key` and `f_nwk_s_int_key` , though they should not be needed when using a device configured to use `LoRaWAN 1.0.3` and `ABP`.

When activating through the interface these keys are internaly set to be the same as the `nwk_s_enc_key` (which can be verified with the `GetDeviceActivationRequest`), but this is not intuitive when calling the API:
- If the provided keys do not match the activation will not work.
- If no keys are supplied at all an "Invalid string length" error is raised.

**Comment by brocaar** [comment]
If you think this can be better documented, them I'm happy to review a PR for this :-) However, I'm not planning to change how this is implemented in the API. While this might look strange, it makes it a lot easier to work with both LoRaWAN 1.0 and LoRaWAN 1.1 internally.

**Comment by tuialexandre** [comment]
Got it. Sure I could do that, thanks!
