### ISSUE TITLE
Replace moment.js

### ISSUE THREAD

**Issue by offizium-berndstorath** [chirpstack/chirpstack#455]
For date formatting [`moment`](https://www.npmjs.com/package/moment) is used.

The project is now in maintenance mode and on the official website they recommend switching to other more modern solutions

https://momentjs.com/docs/#/-project-status/

Bundle size is 1,5% with 58.89 KB (which is not much to the whole bundle, but still fairly large)

**Comment by brocaar** [comment]
Maybe we could do even with the `Date` class itself where possible?
