### ISSUE TITLE
Replace create-react-app

### ISSUE THREAD

**Issue by offizium-berndstorath** [chirpstack/chirpstack#456]
the ui is built using [`create-react-app`](https://github.com/facebook/create-react-app) which is now dead <sup>[1](https://medium.com/@dawid.niegrebecki/create-react-app-is-dead-what-to-use-instead-fcdd46b70295)</sup> <sup>[2](https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741)</sup>

the react team now recommends different tools like full frameworks (next, remix) or vite. I think vite would be the best choice

**Comment by brocaar** [comment]
I had a quick look, and I agree that Vite is probably the best choice.

**Comment by RotaN8** [comment]
> I had a quick look, and I agree that Vite is probably the best choice.

There is a new project that looks promising too: 
https://www.farmfe.org/
https://github.com/farm-fe/farm

If someone wants to check this out. It's fully compatible with Vite plugins also and a so much faster (as it's written in Rust). This project recently released the v1 (stable) so from now it's production ready.

@offizium-berndstorath I see you have already done the migration but if you like the idea it might be a good PR for the future ;)

**Comment by RotaN8** [comment]
> @RotaN8 it indeed looks promising. maybe if it gains some tranction, but otherwise industry standards are good enough imo. vite uses esbuild (go) and swc (rust) so its plenty fast

Totally agree! Only sharing for future consideration maybe ;) Thanks for your PR btw.
