### ISSUE TITLE
Support WASM for Encode and Decode 

### ISSUE THREAD

**Issue by liangyuanpeng** [chirpstack/chirpstack#46]
Chirpstack support to use javascript for custom Encode and custom Decode .

WebAssembly  is other choice for this case, user can use other language to write endcode and decode which they know well , Rust/Go/Javascript/.... , now i just create this issue to tracing this feature.

Maybe we can support it in the future.

**Comment by brocaar** [comment]
While it is interesting, I'm not sure if it is worth the effort. JavaScript has been specified as the language for codecs by the LoRa Alliance. See also https://resources.lora-alliance.org/technical-specifications/ts013-1-0-0-payload-codec-api.

For that reason, I'm closing this issue.
