### ISSUE TITLE
Remove user_info and react-markdown

### ISSUE THREAD

**Issue by offizium-berndstorath** [chirpstack/chirpstack#462]
The package react-markdown is used in the ui for displaying user_info about a region [^1]

This user_info is by default a empty string[^2] and theoretically configurable through the config. but i cant find any information or documentation about this.
[^1]: https://github.com/chirpstack/chirpstack/blob/3777de706da38b19b63141c905db2f61d4533782/ui/src/views/regions/RegionDetails.tsx#L53
[^2]: https://github.com/chirpstack/chirpstack/blob/3777de706da38b19b63141c905db2f61d4533782/chirpstack/src/config.rs#L584

**Comment by brocaar** [comment]
This is a feature that is used (by some of my clients), but it is indeed not documented.
