### ISSUE TITLE
Separate Frontend and Backend

### ISSUE THREAD

**Issue by offizium-berndstorath** [chirpstack/chirpstack#464]
Some people create their own frontend or extend the existing one to match the requirements of their project.

Because the backend url is hardcoded in the frontend, even minor changes would require changes to the stores or a they need to build the entire project

By being able to specify a url in the source code of the ui. one can just build only the ui and deploy it where and how ever they like. Stuff like cors can easily be handled by a reverse proxy

I can create a pr for this if the change would be accepted

**Comment by brocaar** [comment]
> Because the backend url is hardcoded in the frontend, even minor changes would require changes to the stores or a they need to build the entire project

There is no need for it, see this nginx example:
https://github.com/chirpstack/chirpstack-ansible-playbook/blob/master/roles/chirpstack/templates/chirpstack.nginx#L25

The only thing you need to do is to change:

```
	location / {
		proxy_pass http://localhost:8080;
	}
```

to serve the modified UI files from a separate directory. As long as `location ^~ /api` (gRPC API calls) is routed to ChirpStack, that should work and no changes are required to the stores.

**Comment by brocaar** [comment]
I understand that there might be an use-case for this, but I'm not really sure if this should be something that should be solved in the main repo.

**Comment by disarticulate** [comment]
Is there a switch for the server to turn on cors?
