### ISSUE TITLE
Updating is more difficult than it needs to

### ISSUE THREAD

**Issue by offizium-berndstorath** [chirpstack/chirpstack#465]
With most frameworks or apis you specify the identifier of the resource you want to change and then what you want to change.

But with this api you always have to specify everything.

Normal flow: send what to update to server.
Chirpstack flow: get current state. update state. send updated state to server

**Comment by brocaar** [comment]
I'm not sure if this is (easily) fixable. With gRPC fields that are not specified fall back to their default values. E.g. a `bool` type field that is not specified will be interpreted as `false`. It would require an other mechanism (e.g.  specifying a list of fields that one would like to modify), this would require a considerable amount of code-changes which I don't think is worth the effort....

**Comment by bconway** [comment]
There actually is a common pattern for doing partial updates in gRPC using FieldMasks. However, it is almost always used in support of PATCH in grpc-gateway (https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/patch_feature/), and I can't remember having seen it as part of any vanilla gRPC API documentation. I have implemented it myself a bunch of times and it is a fair amount of extra code, as noted. The syntax is also kinda unfriendly to use outside of PATCH.

I do disagree with "most frameworks or apis" defaulting to partial updates, but that's not really important here.
