### ISSUE TITLE
Downlinks missing in events

### ISSUE THREAD

**Issue by oholthau** [chirpstack/chirpstack#471]
Hi All,

we are using Class C devices and send them downlinks depending on a sensor status.
Unfortunately, the downlinks do not appear in the events list. They appear in the LoRaWAN Frames,
but there, you cannot see which payload was sent.

Best regards
Olaf

**Comment by brocaar** [comment]
You will get a txack event, which contains the ID of the downlink + additional metadata: https://www.chirpstack.io/docs/chirpstack/integrations/events.html#txack---downlink-transmission-ack.
