### ISSUE TITLE
Chirpstack does not handle SIGTERM properly

### ISSUE THREAD

**Issue by wouterh** [chirpstack/chirpstack#480]
## Problem description

When chirpstack is run as a container (through docker/kubernetes/...) with a container image build from https://github.com/chirpstack/chirpstack/blob/master/Dockerfile, it ends up running as PID 1 in the container.

The linux kernel handles PID 1 differently:

> The Linux kernel treats PID 1 as a special case, and applies different rules for how it handles signals. This special handling often breaks the assumptions that programs or engineers make.
>
>First, some background. Any process can register its own handlers for TERM and use them to perform cleanup before exiting. If a process hasn’t registered a custom signal handler, the kernel will normally fall back to the default behavior for a TERM signal: killing the process.
>
>For PID 1, though, the kernel won’t fall back to any default behavior when forwarding TERM. If your process hasn’t registered its own handlers (which most processes don’t), TERM will have no effect on the process.

Source: https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html

Chirpstack does not register a SIGTERM handler and as a result both docker and kubernetes are unable to stop chirpstack properly. They do fallback to SIGKILL after a timeout that eventually stops chirpstack, but this is far from an ideal solution. For example in kubernetes, other containers in the pod (e.g. a database proxy) will shutdown on receiving the SIGTERM. Chirpstack stays running until the timeout expires, but some of its dependencies are not available anymore because other containers in the pod have been shut down.

See also the discussion at https://forum.chirpstack.io/t/graceful-shutdown-of-chirpstack/21148/8

## Proposed solution

Chirpstack should register a SIGTERM handler (and SIGINT for ctrl-c ?) and initiate a graceful shutdown on receiving such signal. This would also benefit the case where chirpstack is not running in a container as it allows for cleanup (finishing ongoing transactions, closing database connections, ...) before shutdown.

## Alternative solution

Add a lightweight init system such as `tini` or `dumb-init` to the container to avoid chirpstack being PID 1.

**Comment by bconway** [comment]
Thank you for opening this. I can confirm the problem behavior described.

**Comment by brocaar** [comment]
The above commit adds a signal handler. It should fix the main issue of not responding to SIGTERM.

**Comment by wouterh** [comment]
I have tested v4.9.0 in kubernetes and I can confirm the behavior is now a lot better. Thanks for fixing.
