### ISSUE TITLE
Chirpstack LNS doesn't work in Basic Station mode for RU864 region

### ISSUE THREAD

**Issue by VictorDenisenko** [chirpstack/chirpstack#481]
I unable to get Chirpstack working in Basic Station mode for RU864 region, although it works for the KR920 region.
I used Dragino PG1302+Raspberry Pi3b gateway and three end nodes for RU864 region and LHT65N sensor for KR920 region, in two modes: 
- UDP Packet Forwarder mode and
- Semtech Basic Station mode.
I tried the next Chirpstack variants: 
- ChirpStack Gateway OS;
- [Quickstart Docker Compose](https://www.chirpstack.io/docs/getting-started/docker.html);
- [Quickstart Debian / Ubuntu](https://www.chirpstack.io/docs/getting-started/debian-ubuntu.html) (I used both Ubuntu on remote VPS server and Raspbian on Raspberry Pi in local network).
I tried also TTN LNS.
I tried two region plans: kr920 and ru864 with different end nodes.
Below are the results of my experiments.
1.	All variants work in UDP Packet forwarder mode with Chirpstack and TTN LNS. I see the data receiving from the end nodes.
2.	TTN  LNS works with Semtech Basic Station both for RU864 and KR920 regions.
3.	Chirpstack LNS works with Semtech Basic Station only if I use KR920 region and don’t work when I use RU864 region.
It is why I suppose that RU864 region realized in Chirpstack with errors.
If I try mosquitto_sub -v -t "+/gateway/#", I see UP and DOWN message for KR920 region and don't see them for RU864 region.

Here I attached some files.
[stationRU864.log](https://github.com/user-attachments/files/16569062/stationRU864.log)
[ChirpstackRU864.log](https://github.com/user-attachments/files/16569067/ChirpstackRU864.log)
[ChirpRU864mosquitto_sub.txt](https://github.com/user-attachments/files/16569070/ChirpRU864mosquitto_sub.txt)
[ChirpKR920mosquitto_sub.txt](https://github.com/user-attachments/files/16569071/ChirpKR920mosquitto_sub.txt)
[chirpstack.toml.txt](https://github.com/user-attachments/files/16569105/chirpstack.toml.txt)
[chirpstack-gateway-bridge.toml.txt](https://github.com/user-attachments/files/16569106/chirpstack-gateway-bridge.toml.txt)
![2024-08-10_11-50-59](https://github.com/user-attachments/assets/ff3ff9e8-d056-4cde-bf5f-19e3ada752c9)
![2024-08-10_11-50-19](https://github.com/user-attachments/assets/8e0c7d66-b6df-4a7d-95a5-bb2ff6ca1e5a)

**Comment by brocaar** [comment]
I'm not sure if the Semtech Basics Station has support for RU864, like you already have found out (https://github.com/lorabasics/basicstation/issues/200), searching for `RU864` does not result in any matches. It might be that you can work around this by using `EU868` region with `RU864` frequencies, but then you would run into issues like region specific defaults that might be different.

I will try to reproduce using the ChirpStack Gateway OS + a RU864 development device.

**Comment by brocaar** [comment]
I have tried with the ChirpStack Gateway OS + LoRaMAC-node based test device with RU864 region enabled.

In the ChirpStack Gateway OS (full) I have:

* Configured the Concentratord region to RU864
* Confirmed that the Gateway ID is still present in the footer of the web-interface (Gateway OS / OpenWrt)
* Within ChirpStack I have created a RU864 device-profile
* I have added the RU864 test-device
* I have added the gateway to ChirpStack (not required, but this makes it easy to confirm that the gateway is online)
* Confirmed that the gateway is online
* Confirmed that the device activates and sends data

Please see below screenshot as an example:

![image](https://github.com/user-attachments/assets/c2d80495-8ba8-4a7b-b50a-c9ef09413521)

**Comment by VictorDenisenko** [comment]
Yes, your ChirpStack Gateway OS works with ru864 for me too, but it uses UDP Packet Forwarder and doesn't have option "Semtech Basic Station". Am I right? 
My problem is using Semtech Basic Station with Chirpstack server. Semtech Basic Station works with TTN, but don't work with Chirpstack.

**Comment by VictorDenisenko** [comment]
Maybe, but I entered RU864 name in the TTN web interface. I am trying now to realize your advise with Chirpstack. Now I have connected to Chirpstack using EU868 instead of RU864 (I see green ring in your web UI), but data and connection event from end-device I don’t see. I will try further.

**Comment by VictorDenisenko** [comment]
I was wrong: TTN doesn’t work with my Basic Station for ru864. I saw the data, but gateway disconnects each 2 minutes and reconnects again. Now I check the same with KR920 end-device and it works fine. So, I will try now to change Basic station code for ru864. The reason is not the Chirpstack server. The reason is in Basic Station source code.

**Comment by VictorDenisenko** [comment]
> I'm not sure if the Semtech Basics Station even supports RU864. I scanned through the source-code but there is not a single reference to `RU864`. Could it be that TTN is using the `EU868` common-name, but then with `RU864` frequencies?

Hi Orne, you are right. I have added RU864 region to Basis Station source code and now the problem has been solved.

**Comment by brocaar** [comment]
I'm closing this issue as I believe it was solved by updating the channel config in the ChirpStack Gateway Bridge.
