### ISSUE TITLE
Display UI Version

### ISSUE THREAD

**Issue by offizium-berndstorath** [chirpstack/chirpstack#493]
This is an idea.

Currently the version of chirpstack is displayed in the ui. I mentioned previously that there are use cases where modifying the ui makes sense (#464)

Because of that the version of when the ui was built could differ from the chirpstack (api/backend) version. also maybe a whole different versioning scheme is needed and could be supported by this.

I also think a decision should be made if such cases should be officially supported, documented somewhere or not implemented (this would close #493 and #464)

**Comment by brocaar** [comment]
In an unmodified ChirpStack, there is just one version, the version of ChirpStack.

As the code is MIT licensed, users are free to make modifications such as modifying the UI. As previously mentioned, this can be achieved through for example NGINX rules, that route API request to ChirpStack, but serve UI files from a different directory (serving a modified ChirpStack UI or a complete different UI).

I however do not see why the "mainline" ChirpStack should include configuration to deal with a potentially modified version of the ChirpStack UI. If you make modifications to the ChirpStack UI, then why not include a modification that displays the ChirpStack version using the version obtained from the gRPC API and use a different source for the UI version. As this version most likely comes from a different source (e.g. git revision / tag from your custom repo / fork), I don't see how and why ChirpStack should contain configuration for this.

**Comment by henryliang3027** [comment]
Hi brocaar:
I have the same question. Currently, I'm trying to modify the UI by implementing a dark theme toggle feature. I also want to know how to create my UI based on the current version. What is the best approach to overriding existing styles without affecting the entire server?

I would appreciate any help you can give.
