### ISSUE TITLE
The date calculated in graphs is showing the dayNumber rather than Date

### ISSUE THREAD

**Issue by Malum2600** [chirpstack/chirpstack#503]
In all of the displayed graphs for Gateways and Application devices the date shown as of version 4.9.0 is in the format Month - day number (1-365) instead of Month - day (1-31).  It seems related to UI: Replace moment with date-fns. (https://github.com/chirpstack/chirpstack/pull/460).  I've no solution to offer yet, 

Version 4.8.1
![image](https://github.com/user-attachments/assets/410d2e42-0c86-4810-9e08-64a2bdac7803)

Version 4.9.0
![image](https://github.com/user-attachments/assets/a73bbf2d-3020-4424-960a-dff1a3559e01)

**Comment by brocaar** [comment]
Thanks for reporting, I'll look into this. I think the formatting template is incorrect, this should be an easy fix.

**Comment by brocaar** [comment]
The above commit fixes the issue.
