### ISSUE TITLE
Device Metrics Tooltip Bad Date

### ISSUE THREAD

**Issue by offizium-berndstorath** [chirpstack/chirpstack#517]
If I go to the Device Metrics and hover over a Data Point it shows a bad date

`Sep 263rd`

probably caused by #460

**Comment by brocaar** [comment]
A fix was already implemented, but this hasn't been released yet.  See https://github.com/chirpstack/chirpstack/commit/d69a0eee75422214498cd384340ffc5a5a74baf8
