### ISSUE TITLE
Debian 12

### ISSUE THREAD

**Issue by offizium-berndstorath** [chirpstack/chirpstack#519]
I am planning to upgrade from Debian 11 to Debian 12.

Is Debian 12 supported? Are there any things to consider?

**Comment by Lithimlin** [comment]
Everything should work on Debian 12 as well. I am currently running Chirpstack on Debian 12 and installed it via `apt`.

**Comment by kaaax0815** [comment]
@Lithimlin which postgres version do you use? i had postgres 13 installed which is now replaced by postgres 15

**Comment by Lithimlin** [comment]
I'm on 15, yes

**Comment by brocaar** [comment]
I'm closing this issue as this discussion is more suitable for the forum (answer: it should just work).
