### ISSUE TITLE
Update Title

### ISSUE THREAD

**Issue by kaaax0815** [chirpstack/chirpstack#520]
The Title for all Pages is currently `ChirpStack LoRaWAN® Network-Server`. This makes it very hard to differentiate multiple Tabs and History entries

Please change it to e.g. 
`Name | Device Profiles | ChirpStack LoRaWAN® Network-Server`
`Applications | ChirpStack LoRaWAN® Network-Server`
etc.

**Comment by brocaar** [comment]
I'm open to review a PR for this.
