### ISSUE TITLE
RabbitMQ AMQP Integration

### ISSUE THREAD

**Issue by Lithimlin** [chirpstack/chirpstack#521]
I'm confused about what the AMQP integration actually does and how to use it.

## Expected Behavior

When enabling and configuring the AMQP integration in the `chirpstack.toml`, Chirpstack either

 - Forwards all events to RabbitMQ
 - Gives me the option to tie the integration to a (Chirpstack) application

## Actual Behavior

Chirpstack opens a channel to RabbitMQ but nothing more happens.

## Details

I have a setup with Chirpstack and RabbitMQ. RabbitMQ currently serves as the broker between Chirpstack and the gateways. I now want to write a (3rd-party) application/integration that takes data that arrives in Chirpstack and sends that to an AMQP exchange/queue on my RabbitMQ.

 - Is this possible with the AMQP integration configured in the config file of Chirpstack?
 - Do I just code the 3rd-party application to use the channel that opens between RabbitMQ and chirpstack?
 - Are there examples for such 3rd-party applications somewhere?

**Comment by brocaar** [comment]
The AMQP integration forwards all data to RabbitMQ. Please note that it will publish the data to a routing-key.  In order to receive data, you must subscribe to this routing-key. See also: https://www.chirpstack.io/docs/chirpstack/integrations/amqp.html.
