### ISSUE TITLE
Issue with date shown in tooltip that pop ups in device link metrics

### ISSUE THREAD

**Issue by nicolas-juteau** [chirpstack/chirpstack#528]
The date shown in tooltip that pop ups in device link metrics shows the day of year instead of the day of the month:

![image](https://github.com/user-attachments/assets/6ebd1cc3-d71a-4175-98e2-c0ee19e89ae8)

This issue appears to be introduced in 4.9.0 since with 4.8.1 the date format is ok:

![image](https://github.com/user-attachments/assets/f1d759d5-dd21-4b85-94bd-004da3a306b4)

**Comment by brocaar** [comment]
This has already been fixed, after the v4.9.0 release and will be included in the next release.
