### ISSUE TITLE
Device Queue doesn't happen when Application Integration fails

### ISSUE THREAD

**Issue by NunoSav** [chirpstack/chirpstack#53]
I, for example, have a HTTP integration running in my Application and if the sending of the Uplink data fails for whatever reason the Queue is not dealt with.

After removing the HTTP integration and resending a uplink, the Queue was processed and is now empty.

**Comment by brocaar** [comment]
If I understand correctly:
If the HTTP integration fails, no downlink is being sent from the queue to the device.

I have just setup a HTTP integration to an invalid URL, enqueued a payload in the downlink queue and can confirm that the device still receives the downlink, even if the HTTP integration logs an error.
