### ISSUE TITLE
Issue with Frame Counter 

### ISSUE THREAD

**Issue by Laukik99** [chirpstack/chirpstack#534]
I have disabled the frame counter to perform some tests but still the uplink and downlink frame counters are updating(incrementing).

**Comment by bconway** [comment]
This question would probably be better suited for the help forum.

That being said, I believe the option you're referring to only turns off the frame counter **validation**. It doesn't change the behavior of frame counters, you just won't receive rejections anymore due to the counter validation.

**Comment by brocaar** [comment]
@bconway, that is correct.
