### ISSUE TITLE
Redis password configuration missing

### ISSUE THREAD

**Issue by NunoSav** [chirpstack/chirpstack#54]
I'm setting Chirpstack v4 in a cluster and unless i disable Redis authentication i'm unable to get Chirpstack pod running healthy. Disabling Auth in Redis fixes it.

**Comment by brocaar** [comment]
Doesn't this work to use `password` as password (please adapt number of nodes, IP / hostnames and ports to your own setup)?

```toml
  servers=[
    "redis://:password@127.0.0.1:6379",
    "redis://:password@127.0.0.1:6378",
    "redis://:password@127.0.0.1:6377",  
]
```
