### ISSUE TITLE
Chirpstack Network Server

### ISSUE THREAD

**Issue by MMMatth** [chirpstack/chirpstack#551]
Hello,
I have a quick question: with ChirpStack v4, is it possible to run the LNS (LoRa Network Server) without using the web interface?
Thank you very much!

**Comment by brocaar** [comment]
There is not. If you don't want to expose the web-interface but still want to expose the API, then you could configure a proxy (e.g. NGINX) to only route requests starting with `/api`:

https://github.com/chirpstack/chirpstack-ansible-playbook/blob/master/roles/chirpstack/templates/chirpstack.nginx#L21
