### ISSUE TITLE
Building ChirpStack binaries issue

### ISSUE THREAD

**Issue by Rajkumar181** [chirpstack/chirpstack#554]
when I run make debug-amd64 will meet this error :

sh: line 1: jq: command not found
cross build --target x86_64-unknown-linux-musl --no-default-features --features="postgres"
sh: line 1: cross: command not found
make: *** [Makefile:12: debug-amd64] Error 127

![image](https://github.com/user-attachments/assets/1a36ba52-e491-4363-86b2-706939f9f602)

**Comment by Rajkumar181** [comment]
Thank You for your valuable response.

I have tried to run it but found the same error.

tried 1:

![image](https://github.com/user-attachments/assets/90ff9327-255e-4d97-9cf8-50f13f3fbbd1)

![image](https://github.com/user-attachments/assets/bf322e94-41af-4435-91f9-af02fbbdd9ab)

sh: line 1: jq: command not found
cross build --target x86_64-unknown-linux-musl --release --no-default-features --features="postgres"
sh: line 1: cross: command not found
make: *** [Makefile:15: release-amd64] Error 127

![image](https://github.com/user-attachments/assets/14464d37-8652-4418-a7b9-ab39cc8b21e2)

Please suggest.

**Comment by Rajkumar181** [comment]
Do you mean that I need to install https://github.com/cross-rs/cross and then try?

Still have not yet installed Cross

**Comment by Rajkumar181** [comment]
yes You are right  cross binary is located ~/.cargo/bin/


![image](https://github.com/user-attachments/assets/bffaf5f4-38e0-443f-af63-156d2cc8b198)


where I should add the path and how ?

**Comment by Rajkumar181** [comment]
got different error.

![image](https://github.com/user-attachments/assets/2a871ef0-daf0-45c0-a6fa-f6344725d513)


sh: line 1: jq: command not found
cross build --target x86_64-unknown-linux-musl --release --no-default-features --features="postgres"
info: downloading component 'rust-std' for 'x86_64-unknown-linux-musl'
info: installing component 'rust-std' for 'x86_64-unknown-linux-musl'
 11.8 MiB /  33.0 MiB ( 36 %)   0 B/s in  1s ETA: Unknown                                                          24.8 MiB /  33.0 MiB ( 75 %)  11.8 MiB/s in  2s ETA:  0s                                                          33.0 MiB /  33.0 MiB (100 %)  12.4 MiB/s in  2s ETA:  0s
Error:
   0: no container engine found

Suggestion: is docker or podman installed?
make: *** [Makefile:15: release-amd64] Error 1

**Comment by kaaax0815** [comment]
Please read https://docs.github.com/de/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax to better format your comments

As I said already you have to read the README. in this case https://github.com/chirpstack/chirpstack?tab=readme-ov-file#requirements

If you don't have knowledge about docker, rust and linux why are you trying to build chirpstack yourself?

**Comment by Rajkumar181** [comment]
Thank you. I will follow the GitHub document to format my comments.

There few steps mentioned on README, and I believe, that following those steps, it should compile without error. 

Yes, I am new to Docker but not to Linux, I have made some changes on UI, and that's why I am trying to build.

```
sh: line 1: jq: command not found
cross build --target x86_64-unknown-linux-musl --release --no-default-features --features="postgres"
info: downloading component 'rust-std' for 'x86_64-unknown-linux-musl'
info: installing component 'rust-std' for 'x86_64-unknown-linux-musl'
11.8 MiB / 33.0 MiB ( 36 %) 0 B/s in 1s ETA: Unknown 24.8 MiB / 33.0 MiB ( 75 %) 11.8 MiB/s in 2s ETA: 0s 33.0 MiB / 33.0 MiB (100 %) 12.4 MiB/s in 2s ETA: 0s
Error:
0: no container engine found

Suggestion: is docker or podman installed?
make: *** [Makefile:15: release-amd64] Error 1
```
Docker is already installed on my machine.

**Comment by Rajkumar181** [comment]
jq and Docker are not found in nix-shell



![image](https://github.com/user-attachments/assets/08ce7d6f-5342-41e8-ae98-3fcb185894f5)

**Comment by Rajkumar181** [comment]
Thanks, This is clear to understand, I am trying in nix-shell.

sudo make release-amd64

There some error
```
info: syncing channel updates for '1.79.0-x86_64-unknown-linux-gnu'
info: latest update on 2024-06-13, rust version 1.79.0 (129f3b996 2024-06-10)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
cross build --target x86_64-unknown-linux-musl --release --no-default-features --features="postgres"
/bin/sh: 1: cross: not found
make: *** [Makefile:15: release-amd64] Error 127
```

![image](https://github.com/user-attachments/assets/627c0c64-3526-4098-9445-72ad18bc1432)


I have checked the PATH issue and but looks fine. I have attached.

```
-bash: /home/sharvi/.cargo/bin/:/home/sharvi/.cargo/bin/:/home/sharvi/.cargo/bin:/home/sharvi/.cargo/bin:/home/sharvi/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: No such file or directory
```

**Comment by Rajkumar181** [comment]
Yes you are right.

Now it has built and completed the last step
```
make dist
```
Output:
```
    Building [=======================> ] 554/555: chirpstack(bin)
    Finished `release` profile [optimized] target(s) in 7m 25s
cargo deb --target x86_64-unknown-linux-musl --no-build --no-strip
warning: Command dpkg-shlibdeps failed to launch (no auto deps for /home/sharvi/chirpstack/target/x86_64-unknown-linux-musl/release/chirpstack)
/home/sharvi/chirpstack/target/x86_64-unknown-linux-musl/debian/chirpstack_4.10.1_amd64.deb
cargo deb --target armv7-unknown-linux-musleabihf --no-build --no-strip
warning: Command dpkg-shlibdeps failed to launch (no auto deps for /home/sharvi/chirpstack/target/armv7-unknown-linux-musleabihf/release/chirpstack)
/home/sharvi/chirpstack/target/armv7-unknown-linux-musleabihf/debian/chirpstack_4.10.1_armhf.deb
cargo deb --target aarch64-unknown-linux-musl --no-build --no-strip
warning: Command dpkg-shlibdeps failed to launch (no auto deps for /home/sharvi/chirpstack/target/aarch64-unknown-linux-musl/release/chirpstack)
/home/sharvi/chirpstack/target/aarch64-unknown-linux-musl/debian/chirpstack_4.10.1_arm64.deb
cargo generate-rpm --target x86_64-unknown-linux-musl --target-dir ../target
cargo generate-rpm --target armv7-unknown-linux-musleabihf --target-dir ../target
cargo generate-rpm --target aarch64-unknown-linux-musl --target-dir ../target
mkdir -p ../dist
cp ../target/x86_64-unknown-linux-musl/debian/*.deb ../dist
cp ../target/armv7-unknown-linux-musleabihf/debian/*.deb ../dist
cp ../target/aarch64-unknown-linux-musl/debian/*.deb ../dist
cp ../target/x86_64-unknown-linux-musl/generate-rpm/*.rpm ../dist
cp ../target/armv7-unknown-linux-musleabihf/generate-rpm/*.rpm ../dist
cp ../target/aarch64-unknown-linux-musl/generate-rpm/*.rpm ../dist
tar -czvf ../dist/chirpstack_4.10.1_postgres_amd64.tar.gz -C ../target/x86_64-unknown-linux-musl/release chirpstack
chirpstack
tar -czvf ../dist/chirpstack_4.10.1_postgres_armv7hf.tar.gz -C ../target/armv7-unknown-linux-musleabihf/release chirpstack
chirpstack
tar -czvf ../dist/chirpstack_4.10.1_postgres_arm64.tar.gz -C ../target/aarch64-unknown-linux-musl/release chirpstack
chirpstack
```

There is one warning 

```
warning: Command dpkg-shlibdeps failed to launch (no auto deps for /home/sharvi/chirpstack/target/x86_64-unknown-linux-musl/release/chirpstack)
```

Do I need to follow these steps?

https://github.com/chirpstack/chirpstack?tab=readme-ov-file#database-migrations
