### ISSUE TITLE
Class-C problem

### ISSUE THREAD

**Issue by cyberumut** [chirpstack/chirpstack#559]
im using chirpstack v.4.8.1 

i created device profile and enabled class-c, end node join the this device profile.

i sended queue on chirpstack but i cant see any message on end node 

My end node acting still Class A 

DEBUG schedule{dev_eui=5e9d1e0857cf25c1 downlink_id=3279385687}: chirpstack::downlink::data: Device must send its first uplink first

im using RAK3172 and i activated class-c

**Comment by brocaar** [comment]
> DEBUG schedule{dev_eui=5e9d1e0857cf25c1 downlink_id=3279385687}: chirpstack::downlink::data: Device must send its first uplink first

That should explain your issue. The device must send its first uplink before Class-C will be activated.
