### ISSUE TITLE
Support TimescaleDB / Primary key in Postgres integration

### ISSUE THREAD

**Issue by abalmos** [chirpstack/chirpstack#56]
If you are not familiar, TimescaleDB is an extension for Postgres that improves performance for time series data through their "hypertable" structure. It seems like a good fit for `event_*` tables, particularly, `event_up`. It also offers query functions like `time_bucket` and continuously updated materialized views, which pair quite nicely with Grafana—my goal in this request.

Supporting TimescaleDB should, in theory, just require throwing
```sql
SELECT create_hypertable('event_up', 'time', migrate_data => true);
```
at the database. 

The trouble is that `deduplication_id` is currently a primary key and, therefore, a unique index of `event_*` tables. Due to TimescaleDB's use of Postgres table partitioning, all partition columns must also be part of all unique indexes. In TimescaleDB the time column is always a partition column. As a result, `event_*` tables are not suitable to be converted to a TimescaleDB hypertable.

One solution is to drop the unique (primary key) requirement on the `deduplication_id` column. This seems to work fine, and from what I can tell does not affect Chirpstack. Does `deduplication_id` really need a UNIQUE index on it?

Another solution is to change the primary key to something like `PRIMARY KEY (deduplication_id, time)`. Of course, that changes the semantics and likely isn't your goal here.

Would Chirpstack be willing to change the index on `deduplication_id` for the `event_*` tables to a plain, non-unique one? Perhaps this could be protected behind a TimescaleDB configuration option in the Postgres integration?

**Comment by abalmos** [comment]
@brocaar I agree that the PK is not needed in this case, however, a BRIN index on the time column might be a nice default. The index is very small, yet would have a major impact on SELECTs. I would think `event_up` is generally filtered on `time` in most use cases?

In terms of pairing with Garanfa, `TimescaleDB` is still a better solution (in my opinion) and also open source. While automatic table partitioning helps avoid the ever-increasing insert costs associated with indexes and growing tables, features like `time_bucket` and `time_bucket_gapfil` that avoid sending huge amounts of data to Garfana as time ranges get large are more meaningful.

That said, I don't think Chirpstack should support or even understand TimescaleDb -- just not get in the way. Dropping the PK (which I don't think takes away anything semantically for Chirpstack) and adding a BRIN on time would enable TimescaleDB compatibility and still provide some sane defaults.

Should I open a PR?

As a side note, it would be really great if one could give Chirpstack some external SQL to send after it migrates the database. Right now, it is a bit of a manual process of enabling TimescaleDB /after/ the first start of Chirpstack but before it gets used.

**Comment by brocaar** [comment]
Sorry for the delay.

> Should I open a PR?

Yes please! To create the migration templates, please run the following commands:

```bash
# To enter the Docker devshell
make devshell

# Within Docker environment
cd src/integration/postgresql
diesel migration generate drop_pks_and_add_brin_indices
```

That should generate two files (up and down migration). The down migration should remove the brin indices and restore the PKs.

**Comment by brocaar** [comment]
I looked at this again today, one "issue" that I encountered was that Diesel (the ORM / DB library that I am using) requires a primary key: https://stackoverflow.com/questions/61308862/is-it-possible-to-use-a-table-without-primary-key-in-diesel-rust.

Ideally I want to drop the primary key + add BRIN index on time (which also saves space). Adding a PK on the time column doesn't seem right to me.

I don't think there is any issue when you remove the PK constraint / indices after the first ChirpStack initialization, so maybe this is the easiest solution for now?

**Comment by abalmos** [comment]
That is understandable, and unfortunate about Diesel. It is a bit of an operational wart because you have to change the database _after_ Chripstack is first run, as opposed to the database initialization scripts. We are likely a bit odd in that we bring up new Chirpstack environments in an automated way as part of our “Purdue OATS Data Station” (POD) project. POD is an open source project that tries to make it easy to get started with “cloudless” agricultural IoT, based around LoRaWAN.

I'm okay if this is the long term answer, and happy for you to close the issue.

**Comment by abalmos** [comment]
I should add that I have never seen an issue with modifying the indexes post Chirpstack initialization.

**Comment by brocaar** [comment]
I'm closing this issue as removing the PK after DB initialization should not cause any issues.
