### ISSUE TITLE
error performing TLS handshake with self signed certificate

### ISSUE THREAD

**Issue by RuneRoven** [chirpstack/chirpstack#569]
I am trying to deploy a new chirpstack setup to move over my nodes from the old version to the new 4.10 and in the new system i already have a postgresql running. I am doing i helm chart to run everything in kubernetes. 
The postgres is using a self signed certificate with tls cert and tls key. there is no root CA in the db.
i am using the tls cert for the connection.
The certificate works fine when running psql but in chirpstack i get:
Error: Error occurred while creating a new object: error performing TLS handshake: invalid peer certificate: Other(OtherError(CaUsedAsEndEntity))

if using version 4.6 instead of 4.10 it works.

**Comment by brocaar** [comment]
The `psql` does not strictly validate the server cert by default. The PostgreSQL library used by ChirpStack does. See also this part of the changelog: https://www.chirpstack.io/docs/chirpstack/changelog.html#postgresql-ca-certificate.

I believe if your server cert. is not signed by a (private or public) CA, you can use the certificate itself for your `ca_cert` config.

**Comment by RuneRoven** [comment]
I am using the certificate with the ca_cert option and it does not work. Since it is a self signed certificate using open ssl there is no root CA. Not sure on how to solve this. The certificate comes with the helm chart from umh where the postgres is deployed so i cannot change anything there since it will break other microservices. As of now i am a bit stuck and cannot use the latest version unless i open up postgresl for non tls connection.
