### ISSUE TITLE
Expose through API/MQTT whether device is currently in Class A or Class B

### ISSUE THREAD

**Issue by vitaly-agriocom** [chirpstack/chirpstack#58]
Application may need to know if device is operating in class A or it has upgraded to class B. It would be good if the classB flag would be exposed through MQTT event and in API device service.

**Comment by liangyuanpeng** [comment]
Ref https://forum.chirpstack.io/t/how-to-know-if-device-is-in-class-b/15267

**Comment by brocaar** [comment]
This change adds the `enabled_class` field to the `Device` API message (+ a lot of internal refactoring):

https://github.com/chirpstack/chirpstack/commit/a1a34abaf77b8b54354ee64844ab8e2c078f0a00

**Comment by brocaar** [comment]
I will also add this to the `DeviceInfo` struct of the events:

![image](https://github.com/chirpstack/chirpstack/assets/165497/32b8afdc-c3a2-4233-85f0-c34ef501c83c)

**Comment by brocaar** [comment]
This has been implemented in https://github.com/chirpstack/chirpstack/commit/6480b3bbd554e8deb7b8ca6449b86774dd12aaf9.
