### ISSUE TITLE
[easy] Http Integration multiple URLs separator mistake

### ISSUE THREAD

**Issue by RodionGork** [chirpstack/chirpstack#62]
For integration (streaming events) via HTTP multiple urls could be specified.

In the code they are split with whitespace:

https://github.com/chirpstack/chirpstack/blob/master/chirpstack/src/integration/http.rs#L22

But the hint in the UI for this input field insists it should be comma!

https://github.com/chirpstack/chirpstack/blob/master/ui/src/views/applications/integrations/HttpIntegrationForm.tsx#L46

I would gladly create PR myself but I don't know which way you prefer it to be fixed - either change the code to use comma (slight probability to break some running installation) - or to change the tooltip. I guess the code fix is better as it doesn't make good logic with further whitespace removal.

**Comment by sagar-patel-sls** [comment]
@RodionGork 

I think code fixing (changing the code to use comma) is better than changing the tooltip.

Thanks

**Comment by brocaar** [comment]
Hi @RodionGork, good spot. This indeed should have been split by `','`, not whitespace.
