### ISSUE TITLE
Documentation of MQTT misses devEui field for v4 for downlink commands

### ISSUE THREAD

**Issue by mvniekerk** [chirpstack/chirpstack#72]
https://www.chirpstack.io/application-server/integrations/mqtt/

The devEui field is missing in the documentation as it is required in the payload for downlink commands

**Comment by brocaar** [comment]
You are looking at the v3 documentation, for ChirpStack v4 documentation please see:
https://www.chirpstack.io/docs/chirpstack/integrations/mqtt.html#scheduling-a-downlink
