### ISSUE TITLE
ChirpStack UI does not display version

### ISSUE THREAD

**Issue by alexmaurer-madis** [chirpstack/chirpstack#73]
I didn't see anywhere in the UI the current ChirpStack running version.

Am I blind ?

It could be displayed after the ChirpStack Logo (in the `header.ant-layout-header.layout-header`).

**Comment by brocaar** [comment]
> Am I blind ?

You are not, It is not exposed in the UI, but you can run `chirpstack version` from the CLI. Adding it to the UI would be a feature request.
