### ISSUE TITLE
Store device-sessions in database to simplify backups and disaster-recovery

### ISSUE THREAD

**Issue by timcooijmans** [chirpstack/chirpstack#74]
Currently device-sessions are only stored in redis. When the device-sessions are lost, devices have to re-join, something that is not automated on all devices. The result is that the redis 'database' should be considered persistent-data and should backed-up in addition to the PostgreSQL database.  

It would be easier if the device-sessions would be backed up in the database so only a database-restore is needed as disaster-recovery.

**Comment by IoTThinks** [comment]
Yes, true. Losing device-sessions is a real disaster.

**Comment by timcooijmans** [comment]
@brocaar what is your opinion on this? Is there any architectural reason why device sessions are in redis now?

**Comment by bconway** [comment]
Redis is going to be a lot faster than Postgres for repeated lookups with a predetermined key. I imagine Mr. Brocaar will speak to the full rationale for this design, but personally, I don't think backing up Redis is that big a lift. You should be doing it already if you're in production.

**Comment by timcooijmans** [comment]
>Redis is going to be a lot faster than Postgres for repeated lookups with a predetermined key.

Is this an assumption or did you actually test this? In my experience with production-size PostgreSQL databases and Redis databases the difference on primary-key-based reads is actually negligible between Redis and Postgres. 

Writing is another story due to the integrity guarantees of Postgres, however I guess the PostgreSQL performance would still be sufficient.

**Comment by brocaar** [comment]
Just to let you know, I am doing some testing currently to understand the performance impact of this:
https://github.com/chirpstack/chirpstack/compare/migrate_ds_to_postgres

This might be the best solution to solve #362 as all device-sessions matching a DevAddr can be retrieved in a single query rather than retrieving the DevAddr -> DevEUI set, and then performing one query per key (as we can't use a Redis pipeline as each key might be on a different node in case of Redis Cluster).

**Comment by brocaar** [comment]
This has been implemented in the above commit.

**Comment by timcooijmans** [comment]
Hi @brocaar. Thank you for fixing this. Will test and report back.

Just to confirm, there's no need to back-up Redis anymore after this change, right?

**Comment by brocaar** [comment]
@timcooijmans there is still some data in Redis, like pending mac-commands which could case some issues if not restored (especially when there are RX1Delay, RX1DROffset, RX2DR or RX2Freq changes). Maybe these should be merged into the device-session at some point as well to have everything at one place. However, in the case where all devices are in sync restoring a PostgreSQL backup should recover device connectivity.

**Comment by brocaar** [comment]
Please see: https://forum.chirpstack.io/t/release-chirpstack-v4-7-test-releases/19093
