### ISSUE TITLE
Gateway activity is not consistent on the dashboard

### ISSUE THREAD

**Issue by skiplyfrance** [chirpstack/chirpstack#76]
In the dashboard, the donut chart marks the gateway as inactive 40 seconds after the last stat received. This is probably calculated to match the standard interval of 20 seconds.

On the other hand, markers on the map are marked as inactive after 5 minutes.

See example here:
![0e581687fbb6cf2bdd2cef306dd1df4c33a83bab](https://user-images.githubusercontent.com/19359820/211373391-a902e560-074e-4b9b-936a-432b7e2acf45.jpeg)

It could be interesting to be able to configure the interval after which the gateway could be considered inactive, similar to devices, because the statistics interval can be configured by the user at the gateway level.

Having a common interval of 5 minutes might be a good start.

**Comment by brocaar** [comment]
Thanks @skiplyfrance I agree this should be in sync. I think I was planning to support this, but I have never implemented the stats interval option in the API and UI. There is already a `stats_interval_secs` column in the DB which defaults to 30 seconds.

I will look into this.
