### ISSUE TITLE
CayenneLPP Float Values Zero Decimal

### ISSUE THREAD

**Issue by samtd** [chirpstack/chirpstack#77]
Information from chirpstack with MQTT with .0 decimal. If the value has .0 shouldn't be changed to int?
Strange float values conversions

Current Setup:
chirpstack/chirpstack:4.1
chirpstack/chirpstack-gateway-bridge:4.0
eclipse-mosquitto:2
Device Profile: Class C LorawanV1.03 Codec Cayenne LPP

MQTT -> Chirpstack -> Arduino -> Chirpstack ->MQTT -> Server
Send Message (Arduino):
`{
  "digital_out_11": 1,
  "digital_out_12": 1,
  "digital_out_13": 0,
  "analog_out_1": 1,
  "gyrometer_11": { "x": 123, "y": 0, "z": 0 },
  "gyrometer_12": { "x": 127, "y": 127, "z": 127 },
  "gyrometer_13": { "x": 123.5, "y": 3, "z": 0 },
  "gyrometer_14": { "x": 127, "y": 127, "z": 127 }
}`

Chirpstack:
![imagem](https://user-images.githubusercontent.com/50083198/211378195-7427eb67-3b2d-4791-9dae-af6bb899569d.png)

Received MQTT:
`{
  "analogOutput": { "1": 1.0 },
  "digitalOutput": { "12": 1.0, "11": 1.0, "13": 0.0 },
  "gyrometer": {
    "13": { "y": 3.0, "z": 0.0, "x": 123.5 },
    "11": { "x": 123.0, "y": 0.0, "z": 0.0 },
    "12": { "z": 127.0, "x": 127.0, "y": 127.0 },
    "14": { "y": 127.0, "z": 127.0, "x": 127.0 }
  }
}`

For Digital Outputs the values should be 0 or 1 not 0.0 or 1.0
For example Gyrometer 11 the number should be { "x": 123, "y": 0, "z": 0 } not { "x": 123.0, "y": 0.0, "z": 0.0 }
It’s normal de order xyz change to yzx or zxy

Server -> MQTT -> Chirpstack -> Arduino
Send Message:
`{
  "devEui": "a8610a3337306e0c",
  "confirmed": true,
  "fPort": 2,
  "object": {
    "analogOutput": { "1": 101, "31": 0, "103": 2.3, "104": 10.0 },
    "digitalInput": { "31": 0, "103": 1, "104": 0, "110": 0, "112": 1 },
    "digitalOutput": { "31": 1 },
    "analogInput": { "109": 0, "105": 1.3 },
    "gyrometer": { "104": { "x": 0.7, "y": 81.5, "z": 41.5 } }
  }
}`

Received:
`{
  "digital_in_31": 0,
  "digital_in_103": 1,
  "digital_in_104": 0,
  "digital_in_110": 0,
  "digital_in_112": 1,
  "digital_out_31": 1,
  "analog_in_105": 1.299999952,
  "analog_in_109": 0,
  "analog_out_1": 101,
  "analog_out_31": 0,
  "analog_out_103": 2.289999962,
  "analog_out_104": 10,
  "gyrometer_104": { "x": 0.699999988, "y": 81.5, "z": 41.5 }
}`

I send analogInput: "105": 1.3, and received "analog_in_105": 1.299999952,
I send analogOutput "103": 2.3 and received "analog_out_103": 2.289999962,
I send gyrometer": { "104": { "x": 0.7, and received  "gyrometer_104": { "x": 0.699999988,

Another example with full message:
```
{
  "deduplicationId": "-",
  "time": "2023-01-09T18:19:38.662433378+00:00",
  "deviceInfo": {
    "tenantId": "-",
    "tenantName": "ChirpStack",
    "applicationId": "-",
    "applicationName": "Modulos_Rega",
    "deviceProfileId": "-",
    "deviceProfileName": "IOTDEVC",
    "deviceName": "Rega_06",
    "devEui": "-",
    "tags": {}
  },
  "devAddr": "-",
  "adr": true,
  "dr": 5,
  "fCnt": 16,
  "fPort": 2,
  "confirmed": true,
  "data": "AQMAZAsBAQwBAQ0BAAuGMAwAAAAADIYxnDGcMZwNhjA+ASwAAA6GMZwxnDGc",
  "object": {
    "gyrometer": {
      "14": { "y": 127.0, "z": 127.0, "x": 127.0 },
      "11": { "x": 123.0, "y": 0.0, "z": 0.0 },
      "12": { "x": 127.0, "z": 127.0, "y": 127.0 },
      "13": { "y": 3.0, "z": 0.0, "x": 123.5 }
    },
    "analogOutput": { "1": 1.0 },
    "digitalOutput": { "12": 1.0, "13": 0.0, "11": 1.0 }
  },
  "rxInfo": [
    {
      "gatewayId": "-",
      "uplinkId": 24309,
      "rssi": -75,
      "snr": 10.8,
      "channel": 3,
      "location": {},
      "context": "fw5lSw==",
      "metadata": { "region_name": "eu868", "region_common_name": "EU868" }
    }
  ],
  "txInfo": {
    "frequency": 867100000,
    "modulation": {
      "lora": {
        "bandwidth": 125000,
        "spreadingFactor": 7,
        "codeRate": "CR_4_5"
      }
    }
  }
}
```
![imagem](https://user-images.githubusercontent.com/50083198/211380780-b9d66659-d4fe-4d12-92a6-73d2cfaa4041.png)

**Comment by brocaar** [comment]
> For Digital Outputs the values should be 0 or 1 not 0.0 or 1.0

The output of the Cayenne LPP decoder in ChirpStack is of type `u8`, but to convert it to JSON, it is converted into the JSON number type (float). As JSON does not have distinct types for float or integer, this `u8` value is converted to float which is why you are seeing `1` being represented as `1.0`. Over the wire, the correct information is transmitted, but because of the transformation to JSON you loose some information (float vs integer).

> For example Gyrometer 11 the number should be { "x": 123, "y": 0, "z": 0 } not { "x": 123.0, "y": 0.0, "z": 0.0 }

Same as above.

> It’s normal de order xyz change to yzx or zxy

Yes, the keys are by name so you must parse them by name. There is no guarantee that keys are ordered, consider the order random.

> I send analogInput: "105": 1.3, and received "analog_in_105": 1.299999952,
> I send analogOutput "103": 2.3 and received "analog_out_103": 2.289999962,
> I send gyrometer": { "104": { "x": 0.7, and received "gyrometer_104": { "x": 0.699999988,

Welcome to the wonderful world of float values :-) I believe the values that you see are correct and are due to how floats work. You can test this also here: https://www.h-schmidt.net/FloatConverter/IEEE754.html.

**Comment by stefanbraun-private** [comment]
Hello,
I found a similar problem:
All integers in a ChirpStack payload decoder ("Codec") are converted to floats, when using HTTP integration...

I added some constant test-values like "2" and "2.0",
and the receiving webhook got the same raw values in the JSON message.

=>I'm wondering why integers in metadata (like "fCnt", "fPort", "dr") have no decimals in JSON message,
and my integers from payload decoder always gets converted to float?

This is what the receiving webhook gets:

```
"dr": 2,
"fCnt": 4562,
"fPort": 5,
[...]
"object":
{
    "test_int": 2.0,
    "test_float": 2.0,
    
    "latitude": 47.4,
    "longitude": 9.3,
    "accuracy": 12.0,
    "altitude": 0.0,
    "app_eui": "476d......",
    [...]
}

```

![ChirpStack Event Debugging](https://github.com/chirpstack/chirpstack/assets/22547904/f7d741a6-1c25-4868-93fb-e497111bfb0f)

**Comment by brocaar** [comment]
Please read my above answer, it applies to your question as well I believe.

**Comment by stefanbraun-private** [comment]
> Please read my above answer, it applies to your question as well I believe.

Thank your for your time and your response! :-)
Yes, I understand that every integer gets converted to float when transmitting as JSON.

But I'm still wondering why integers in metadata (like "fCnt", "fPort", "dr") have no decimals in JSON message...
Example is in screenshot in my posting https://github.com/chirpstack/chirpstack/issues/77#issuecomment-2067683930
(it's not an issue, I'm just trying to understand)

**Comment by brocaar** [comment]
The Protobuf > JSON is generated by https://docs.rs/pbjson/latest/pbjson/. I expect that they might do some formatting as from the Protobuf side it is known if decimals are needed or not.

From the codec side, numeric values are using the `NumberValue`: https://docs.rs/pbjson-types/latest/pbjson_types/value/enum.Kind.html#variant.NumberValue.

See also: https://github.com/chirpstack/chirpstack/blob/master/chirpstack/src/codec/convert.rs#L12
