### ISSUE TITLE
Packages for other Operating Systems

### ISSUE THREAD

**Issue by phlipse** [chirpstack/chirpstack#87]
Hello ChirpStack project,

is it planned to provide further pre-built packages for further operating systems like CentOS or even FreeBSD, OpenBSD or NetBSD?
Currently only Ubuntu / Debian is available.

I would be interested in FreeBSD.

**Comment by brocaar** [comment]
Please note that `.rpm` packages are available, so  RedHat / CentOS should already be covered? As well you can download `.tar.gz` archives with pre-compiled binaries which are not tied to a specific Linux flavor (see the downloads section in the docs).

I don't have any experience with FreeBSD / OpenBSD or NetBSD and providing pre-compiled binaries for these platforms is currently not on my backlog.
